package com.google.android.gms.internal.mlkit_common;

import com.github.junrar.unpack.ppm.ModelPPM;
import com.google.mlkit.common.MlKitException;
import java.util.HashMap;
/* compiled from: r8-map-id-0dd4387375ec438f6a4c042bfe6cb4a3262713dcd4829883cccf19288831b1df */
/* loaded from: classes.dex */
final class zzgp implements qh4 {
    private static final na2 zzA;
    private static final na2 zzB;
    private static final na2 zzC;
    private static final na2 zzD;
    private static final na2 zzE;
    private static final na2 zzF;
    private static final na2 zzG;
    private static final na2 zzH;
    private static final na2 zzI;
    private static final na2 zzJ;
    private static final na2 zzK;
    private static final na2 zzL;
    private static final na2 zzM;
    private static final na2 zzN;
    private static final na2 zzO;
    private static final na2 zzP;
    private static final na2 zzQ;
    private static final na2 zzR;
    private static final na2 zzS;
    private static final na2 zzT;
    private static final na2 zzU;
    private static final na2 zzV;
    private static final na2 zzW;
    private static final na2 zzX;
    private static final na2 zzY;
    private static final na2 zzZ;
    static final zzgp zza = new zzgp();
    private static final na2 zzaA;
    private static final na2 zzaB;
    private static final na2 zzaC;
    private static final na2 zzaD;
    private static final na2 zzaE;
    private static final na2 zzaF;
    private static final na2 zzaG;
    private static final na2 zzaH;
    private static final na2 zzaI;
    private static final na2 zzaJ;
    private static final na2 zzaK;
    private static final na2 zzaL;
    private static final na2 zzaM;
    private static final na2 zzaN;
    private static final na2 zzaO;
    private static final na2 zzaP;
    private static final na2 zzaQ;
    private static final na2 zzaR;
    private static final na2 zzaS;
    private static final na2 zzaT;
    private static final na2 zzaU;
    private static final na2 zzaV;
    private static final na2 zzaW;
    private static final na2 zzaX;
    private static final na2 zzaY;
    private static final na2 zzaZ;
    private static final na2 zzaa;
    private static final na2 zzab;
    private static final na2 zzac;
    private static final na2 zzad;
    private static final na2 zzae;
    private static final na2 zzaf;
    private static final na2 zzag;
    private static final na2 zzah;
    private static final na2 zzai;
    private static final na2 zzaj;
    private static final na2 zzak;
    private static final na2 zzal;
    private static final na2 zzam;
    private static final na2 zzan;
    private static final na2 zzao;
    private static final na2 zzap;
    private static final na2 zzaq;
    private static final na2 zzar;
    private static final na2 zzas;
    private static final na2 zzat;
    private static final na2 zzau;
    private static final na2 zzav;
    private static final na2 zzaw;
    private static final na2 zzax;
    private static final na2 zzay;
    private static final na2 zzaz;
    private static final na2 zzb;
    private static final na2 zzba;
    private static final na2 zzbb;
    private static final na2 zzbc;
    private static final na2 zzbd;
    private static final na2 zzbe;
    private static final na2 zzbf;
    private static final na2 zzbg;
    private static final na2 zzbh;
    private static final na2 zzbi;
    private static final na2 zzbj;
    private static final na2 zzbk;
    private static final na2 zzbl;
    private static final na2 zzbm;
    private static final na2 zzbn;
    private static final na2 zzbo;
    private static final na2 zzbp;
    private static final na2 zzbq;
    private static final na2 zzbr;
    private static final na2 zzbs;
    private static final na2 zzbt;
    private static final na2 zzbu;
    private static final na2 zzbv;
    private static final na2 zzbw;
    private static final na2 zzbx;
    private static final na2 zzby;
    private static final na2 zzc;
    private static final na2 zzd;
    private static final na2 zze;
    private static final na2 zzf;
    private static final na2 zzg;
    private static final na2 zzh;
    private static final na2 zzi;
    private static final na2 zzj;
    private static final na2 zzk;
    private static final na2 zzl;
    private static final na2 zzm;
    private static final na2 zzn;
    private static final na2 zzo;
    private static final na2 zzp;
    private static final na2 zzq;
    private static final na2 zzr;
    private static final na2 zzs;
    private static final na2 zzt;
    private static final na2 zzu;
    private static final na2 zzv;
    private static final na2 zzw;
    private static final na2 zzx;
    private static final na2 zzy;
    private static final na2 zzz;

    static {
        zzbc h = xg6.h(1);
        HashMap hashMap = new HashMap();
        hashMap.put(h.annotationType(), h);
        zzb = new na2("systemInfo", xg6.u(hashMap));
        zzbc h2 = xg6.h(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(h2.annotationType(), h2);
        zzc = new na2("eventName", xg6.u(hashMap2));
        zzbc h3 = xg6.h(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(h3.annotationType(), h3);
        zzd = new na2("isThickClient", xg6.u(hashMap3));
        zzbc h4 = xg6.h(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(h4.annotationType(), h4);
        zze = new na2("clientType", xg6.u(hashMap4));
        zzbc h5 = xg6.h(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(h5.annotationType(), h5);
        zzf = new na2("modelDownloadLogEvent", xg6.u(hashMap5));
        zzbc h6 = xg6.h(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(h6.annotationType(), h6);
        zzg = new na2("customModelLoadLogEvent", xg6.u(hashMap6));
        zzbc h7 = xg6.h(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(h7.annotationType(), h7);
        zzh = new na2("customModelInferenceLogEvent", xg6.u(hashMap7));
        zzbc h8 = xg6.h(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(h8.annotationType(), h8);
        zzi = new na2("customModelCreateLogEvent", xg6.u(hashMap8));
        zzbc h9 = xg6.h(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(h9.annotationType(), h9);
        zzj = new na2("onDeviceFaceDetectionLogEvent", xg6.u(hashMap9));
        zzbc h10 = xg6.h(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(h10.annotationType(), h10);
        zzk = new na2("onDeviceFaceLoadLogEvent", xg6.u(hashMap10));
        zzbc h11 = xg6.h(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(h11.annotationType(), h11);
        zzl = new na2("onDeviceTextDetectionLogEvent", xg6.u(hashMap11));
        zzbc h12 = xg6.h(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(h12.annotationType(), h12);
        zzm = new na2("onDeviceTextDetectionLoadLogEvent", xg6.u(hashMap12));
        zzbc h13 = xg6.h(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(h13.annotationType(), h13);
        zzn = new na2("onDeviceBarcodeDetectionLogEvent", xg6.u(hashMap13));
        zzbc h14 = xg6.h(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(h14.annotationType(), h14);
        zzo = new na2("onDeviceBarcodeLoadLogEvent", xg6.u(hashMap14));
        zzbc h15 = xg6.h(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(h15.annotationType(), h15);
        zzp = new na2("onDeviceImageLabelCreateLogEvent", xg6.u(hashMap15));
        zzbc h16 = xg6.h(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(h16.annotationType(), h16);
        zzq = new na2("onDeviceImageLabelLoadLogEvent", xg6.u(hashMap16));
        zzbc h17 = xg6.h(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(h17.annotationType(), h17);
        zzr = new na2("onDeviceImageLabelDetectionLogEvent", xg6.u(hashMap17));
        zzbc h18 = xg6.h(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(h18.annotationType(), h18);
        zzs = new na2("onDeviceObjectCreateLogEvent", xg6.u(hashMap18));
        zzbc h19 = xg6.h(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(h19.annotationType(), h19);
        zzt = new na2("onDeviceObjectLoadLogEvent", xg6.u(hashMap19));
        zzbc h20 = xg6.h(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(h20.annotationType(), h20);
        zzu = new na2("onDeviceObjectInferenceLogEvent", xg6.u(hashMap20));
        zzbc h21 = xg6.h(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(h21.annotationType(), h21);
        zzv = new na2("onDevicePoseDetectionLogEvent", xg6.u(hashMap21));
        zzbc h22 = xg6.h(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(h22.annotationType(), h22);
        zzw = new na2("onDeviceSegmentationLogEvent", xg6.u(hashMap22));
        zzbc h23 = xg6.h(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(h23.annotationType(), h23);
        zzx = new na2("onDeviceSmartReplyLogEvent", xg6.u(hashMap23));
        zzbc h24 = xg6.h(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(h24.annotationType(), h24);
        zzy = new na2("onDeviceLanguageIdentificationLogEvent", xg6.u(hashMap24));
        zzbc h25 = xg6.h(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(h25.annotationType(), h25);
        zzz = new na2("onDeviceTranslationLogEvent", xg6.u(hashMap25));
        zzbc h26 = xg6.h(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(h26.annotationType(), h26);
        zzA = new na2("cloudFaceDetectionLogEvent", xg6.u(hashMap26));
        zzbc h27 = xg6.h(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(h27.annotationType(), h27);
        zzB = new na2("cloudCropHintDetectionLogEvent", xg6.u(hashMap27));
        zzbc h28 = xg6.h(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(h28.annotationType(), h28);
        zzC = new na2("cloudDocumentTextDetectionLogEvent", xg6.u(hashMap28));
        zzbc h29 = xg6.h(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(h29.annotationType(), h29);
        zzD = new na2("cloudImagePropertiesDetectionLogEvent", xg6.u(hashMap29));
        zzbc h30 = xg6.h(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(h30.annotationType(), h30);
        zzE = new na2("cloudImageLabelDetectionLogEvent", xg6.u(hashMap30));
        zzbc h31 = xg6.h(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(h31.annotationType(), h31);
        zzF = new na2("cloudLandmarkDetectionLogEvent", xg6.u(hashMap31));
        zzbc h32 = xg6.h(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(h32.annotationType(), h32);
        zzG = new na2("cloudLogoDetectionLogEvent", xg6.u(hashMap32));
        zzbc h33 = xg6.h(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(h33.annotationType(), h33);
        zzH = new na2("cloudSafeSearchDetectionLogEvent", xg6.u(hashMap33));
        zzbc h34 = xg6.h(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(h34.annotationType(), h34);
        zzI = new na2("cloudTextDetectionLogEvent", xg6.u(hashMap34));
        zzbc h35 = xg6.h(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(h35.annotationType(), h35);
        zzJ = new na2("cloudWebSearchDetectionLogEvent", xg6.u(hashMap35));
        zzbc h36 = xg6.h(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(h36.annotationType(), h36);
        zzK = new na2("automlImageLabelingCreateLogEvent", xg6.u(hashMap36));
        zzbc h37 = xg6.h(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(h37.annotationType(), h37);
        zzL = new na2("automlImageLabelingLoadLogEvent", xg6.u(hashMap37));
        zzbc h38 = xg6.h(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(h38.annotationType(), h38);
        zzM = new na2("automlImageLabelingInferenceLogEvent", xg6.u(hashMap38));
        zzbc h39 = xg6.h(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(h39.annotationType(), h39);
        zzN = new na2("isModelDownloadedLogEvent", xg6.u(hashMap39));
        zzbc h40 = xg6.h(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(h40.annotationType(), h40);
        zzO = new na2("deleteModelLogEvent", xg6.u(hashMap40));
        zzbc h41 = xg6.h(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(h41.annotationType(), h41);
        zzP = new na2("aggregatedAutomlImageLabelingInferenceLogEvent", xg6.u(hashMap41));
        zzbc h42 = xg6.h(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(h42.annotationType(), h42);
        zzQ = new na2("aggregatedCustomModelInferenceLogEvent", xg6.u(hashMap42));
        zzbc h43 = xg6.h(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(h43.annotationType(), h43);
        zzR = new na2("aggregatedOnDeviceFaceDetectionLogEvent", xg6.u(hashMap43));
        zzbc h44 = xg6.h(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(h44.annotationType(), h44);
        zzS = new na2("aggregatedOnDeviceBarcodeDetectionLogEvent", xg6.u(hashMap44));
        zzbc h45 = xg6.h(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(h45.annotationType(), h45);
        zzT = new na2("aggregatedOnDeviceImageLabelDetectionLogEvent", xg6.u(hashMap45));
        zzbc h46 = xg6.h(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(h46.annotationType(), h46);
        zzU = new na2("aggregatedOnDeviceObjectInferenceLogEvent", xg6.u(hashMap46));
        zzbc h47 = xg6.h(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(h47.annotationType(), h47);
        zzV = new na2("aggregatedOnDeviceTextDetectionLogEvent", xg6.u(hashMap47));
        zzbc h48 = xg6.h(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(h48.annotationType(), h48);
        zzW = new na2("aggregatedOnDevicePoseDetectionLogEvent", xg6.u(hashMap48));
        zzbc h49 = xg6.h(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(h49.annotationType(), h49);
        zzX = new na2("aggregatedOnDeviceSegmentationLogEvent", xg6.u(hashMap49));
        zzbc h50 = xg6.h(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(h50.annotationType(), h50);
        zzY = new na2("pipelineAccelerationInferenceEvents", xg6.u(hashMap50));
        zzbc h51 = xg6.h(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(h51.annotationType(), h51);
        zzZ = new na2("remoteConfigLogEvent", xg6.u(hashMap51));
        zzbc h52 = xg6.h(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(h52.annotationType(), h52);
        zzaa = new na2("inputImageConstructionLogEvent", xg6.u(hashMap52));
        zzbc h53 = xg6.h(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(h53.annotationType(), h53);
        zzab = new na2("leakedHandleEvent", xg6.u(hashMap53));
        zzbc h54 = xg6.h(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(h54.annotationType(), h54);
        zzac = new na2("cameraSourceLogEvent", xg6.u(hashMap54));
        zzbc h55 = xg6.h(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(h55.annotationType(), h55);
        zzad = new na2("imageLabelOptionalModuleLogEvent", xg6.u(hashMap55));
        zzbc h56 = xg6.h(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(h56.annotationType(), h56);
        zzae = new na2("languageIdentificationOptionalModuleLogEvent", xg6.u(hashMap56));
        zzbc h57 = xg6.h(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(h57.annotationType(), h57);
        zzaf = new na2("faceDetectionOptionalModuleLogEvent", xg6.u(hashMap57));
        zzbc h58 = xg6.h(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(h58.annotationType(), h58);
        zzag = new na2("documentDetectionOptionalModuleLogEvent", xg6.u(hashMap58));
        zzbc h59 = xg6.h(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(h59.annotationType(), h59);
        zzah = new na2("documentCroppingOptionalModuleLogEvent", xg6.u(hashMap59));
        zzbc h60 = xg6.h(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(h60.annotationType(), h60);
        zzai = new na2("documentEnhancementOptionalModuleLogEvent", xg6.u(hashMap60));
        zzbc h61 = xg6.h(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(h61.annotationType(), h61);
        zzaj = new na2("nlClassifierOptionalModuleLogEvent", xg6.u(hashMap61));
        zzbc h62 = xg6.h(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(h62.annotationType(), h62);
        zzak = new na2("nlClassifierClientLibraryLogEvent", xg6.u(hashMap62));
        zzbc h63 = xg6.h(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(h63.annotationType(), h63);
        zzal = new na2("accelerationAllowlistLogEvent", xg6.u(hashMap63));
        zzbc h64 = xg6.h(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(h64.annotationType(), h64);
        zzam = new na2("toxicityDetectionCreateEvent", xg6.u(hashMap64));
        zzbc h65 = xg6.h(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(h65.annotationType(), h65);
        zzan = new na2("toxicityDetectionLoadEvent", xg6.u(hashMap65));
        zzbc h66 = xg6.h(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(h66.annotationType(), h66);
        zzao = new na2("toxicityDetectionInferenceEvent", xg6.u(hashMap66));
        zzbc h67 = xg6.h(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(h67.annotationType(), h67);
        zzap = new na2("barcodeDetectionOptionalModuleLogEvent", xg6.u(hashMap67));
        zzbc h68 = xg6.h(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(h68.annotationType(), h68);
        zzaq = new na2("customImageLabelOptionalModuleLogEvent", xg6.u(hashMap68));
        zzbc h69 = xg6.h(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(h69.annotationType(), h69);
        zzar = new na2("codeScannerScanApiEvent", xg6.u(hashMap69));
        zzbc h70 = xg6.h(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(h70.annotationType(), h70);
        zzas = new na2("codeScannerOptionalModuleEvent", xg6.u(hashMap70));
        zzbc h71 = xg6.h(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(h71.annotationType(), h71);
        zzat = new na2("onDeviceExplicitContentCreateLogEvent", xg6.u(hashMap71));
        zzbc h72 = xg6.h(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(h72.annotationType(), h72);
        zzau = new na2("onDeviceExplicitContentLoadLogEvent", xg6.u(hashMap72));
        zzbc h73 = xg6.h(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(h73.annotationType(), h73);
        zzav = new na2("onDeviceExplicitContentInferenceLogEvent", xg6.u(hashMap73));
        zzbc h74 = xg6.h(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(h74.annotationType(), h74);
        zzaw = new na2("aggregatedOnDeviceExplicitContentLogEvent", xg6.u(hashMap74));
        zzbc h75 = xg6.h(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(h75.annotationType(), h75);
        zzax = new na2("onDeviceFaceMeshCreateLogEvent", xg6.u(hashMap75));
        zzbc h76 = xg6.h(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(h76.annotationType(), h76);
        zzay = new na2("onDeviceFaceMeshLoadLogEvent", xg6.u(hashMap76));
        zzbc h77 = xg6.h(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(h77.annotationType(), h77);
        zzaz = new na2("onDeviceFaceMeshLogEvent", xg6.u(hashMap77));
        zzbc h78 = xg6.h(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(h78.annotationType(), h78);
        zzaA = new na2("aggregatedOnDeviceFaceMeshLogEvent", xg6.u(hashMap78));
        zzbc h79 = xg6.h(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(h79.annotationType(), h79);
        zzaB = new na2("smartReplyOptionalModuleLogEvent", xg6.u(hashMap79));
        zzbc h80 = xg6.h(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(h80.annotationType(), h80);
        zzaC = new na2("textDetectionOptionalModuleLogEvent", xg6.u(hashMap80));
        zzbc h81 = xg6.h(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(h81.annotationType(), h81);
        zzaD = new na2("onDeviceImageQualityAnalysisCreateLogEvent", xg6.u(hashMap81));
        zzbc h82 = xg6.h(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(h82.annotationType(), h82);
        zzaE = new na2("onDeviceImageQualityAnalysisLoadLogEvent", xg6.u(hashMap82));
        zzbc h83 = xg6.h(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(h83.annotationType(), h83);
        zzaF = new na2("onDeviceImageQualityAnalysisLogEvent", xg6.u(hashMap83));
        zzbc h84 = xg6.h(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(h84.annotationType(), h84);
        zzaG = new na2("aggregatedOnDeviceImageQualityAnalysisLogEvent", xg6.u(hashMap84));
        zzbc h85 = xg6.h(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(h85.annotationType(), h85);
        zzaH = new na2("imageQualityAnalysisOptionalModuleLogEvent", xg6.u(hashMap85));
        zzbc h86 = xg6.h(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(h86.annotationType(), h86);
        zzaI = new na2("imageCaptioningOptionalModuleLogEvent", xg6.u(hashMap86));
        zzbc h87 = xg6.h(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(h87.annotationType(), h87);
        zzaJ = new na2("onDeviceImageCaptioningCreateLogEvent", xg6.u(hashMap87));
        zzbc h88 = xg6.h(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(h88.annotationType(), h88);
        zzaK = new na2("onDeviceImageCaptioningLoadLogEvent", xg6.u(hashMap88));
        zzbc h89 = xg6.h(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(h89.annotationType(), h89);
        zzaL = new na2("onDeviceImageCaptioningInferenceLogEvent", xg6.u(hashMap89));
        zzbc h90 = xg6.h(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(h90.annotationType(), h90);
        zzaM = new na2("aggregatedOnDeviceImageCaptioningInferenceLogEvent", xg6.u(hashMap90));
        zzbc h91 = xg6.h(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(h91.annotationType(), h91);
        zzaN = new na2("onDeviceDocumentDetectionCreateLogEvent", xg6.u(hashMap91));
        zzbc h92 = xg6.h(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(h92.annotationType(), h92);
        zzaO = new na2("onDeviceDocumentDetectionLoadLogEvent", xg6.u(hashMap92));
        zzbc h93 = xg6.h(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(h93.annotationType(), h93);
        zzaP = new na2("onDeviceDocumentDetectionLogEvent", xg6.u(hashMap93));
        zzbc h94 = xg6.h(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(h94.annotationType(), h94);
        zzaQ = new na2("aggregatedOnDeviceDocumentDetectionLogEvent", xg6.u(hashMap94));
        zzbc h95 = xg6.h(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(h95.annotationType(), h95);
        zzaR = new na2("onDeviceDocumentCroppingCreateLogEvent", xg6.u(hashMap95));
        zzbc h96 = xg6.h(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(h96.annotationType(), h96);
        zzaS = new na2("onDeviceDocumentCroppingLoadLogEvent", xg6.u(hashMap96));
        zzbc h97 = xg6.h(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(h97.annotationType(), h97);
        zzaT = new na2("onDeviceDocumentCroppingLogEvent", xg6.u(hashMap97));
        zzbc h98 = xg6.h(MlKitException.NOT_ENOUGH_SPACE);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(h98.annotationType(), h98);
        zzaU = new na2("aggregatedOnDeviceDocumentCroppingLogEvent", xg6.u(hashMap98));
        zzbc h99 = xg6.h(MlKitException.MODEL_HASH_MISMATCH);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(h99.annotationType(), h99);
        zzaV = new na2("onDeviceDocumentEnhancementCreateLogEvent", xg6.u(hashMap99));
        zzbc h100 = xg6.h(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(h100.annotationType(), h100);
        zzaW = new na2("onDeviceDocumentEnhancementLoadLogEvent", xg6.u(hashMap100));
        zzbc h101 = xg6.h(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(h101.annotationType(), h101);
        zzaX = new na2("onDeviceDocumentEnhancementLogEvent", xg6.u(hashMap101));
        zzbc h102 = xg6.h(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(h102.annotationType(), h102);
        zzaY = new na2("aggregatedOnDeviceDocumentEnhancementLogEvent", xg6.u(hashMap102));
        zzbc h103 = xg6.h(106);
        HashMap hashMap103 = new HashMap();
        hashMap103.put(h103.annotationType(), h103);
        zzaZ = new na2("scannerAutoZoomEvent", xg6.u(hashMap103));
        zzbc h104 = xg6.h(107);
        HashMap hashMap104 = new HashMap();
        hashMap104.put(h104.annotationType(), h104);
        zzba = new na2("lowLightAutoExposureComputationEvent", xg6.u(hashMap104));
        zzbc h105 = xg6.h(108);
        HashMap hashMap105 = new HashMap();
        hashMap105.put(h105.annotationType(), h105);
        zzbb = new na2("lowLightFrameProcessEvent", xg6.u(hashMap105));
        zzbc h106 = xg6.h(109);
        HashMap hashMap106 = new HashMap();
        hashMap106.put(h106.annotationType(), h106);
        zzbc = new na2("lowLightSceneDetectionEvent", xg6.u(hashMap106));
        zzbc h107 = xg6.h(110);
        HashMap hashMap107 = new HashMap();
        hashMap107.put(h107.annotationType(), h107);
        zzbd = new na2("onDeviceStainRemovalLogEvent", xg6.u(hashMap107));
        zzbc h108 = xg6.h(111);
        HashMap hashMap108 = new HashMap();
        hashMap108.put(h108.annotationType(), h108);
        zzbe = new na2("aggregatedOnDeviceStainRemovalLogEvent", xg6.u(hashMap108));
        zzbf = xg6.g(112, na2.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = xg6.g(113, na2.a("onDeviceShadowRemovalLogEvent"));
        zzbh = xg6.g(114, na2.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = xg6.g(115, na2.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = xg6.g(116, na2.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = xg6.g(117, na2.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = xg6.g(118, na2.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = xg6.g(119, na2.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = xg6.g(120, na2.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = xg6.g(121, na2.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = xg6.g(122, na2.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = xg6.g(123, na2.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = xg6.g(ModelPPM.MAX_FREQ, na2.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = xg6.g(125, na2.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = xg6.g(126, na2.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = xg6.g(127, na2.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = xg6.g(128, na2.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = xg6.g(129, na2.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = xg6.g(130, na2.a("documentScannerUiModuleScreenClickEvent"));
        zzby = xg6.g(131, na2.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzgp() {
    }

    @Override // defpackage.y32
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzmy zzmyVar = (zzmy) obj;
        rh4 rh4Var = (rh4) obj2;
        rh4Var.add(zzb, zzmyVar.zzf());
        rh4Var.add(zzc, zzmyVar.zzd());
        rh4Var.add(zzd, (Object) null);
        rh4Var.add(zze, (Object) null);
        rh4Var.add(zzf, zzmyVar.zze());
        rh4Var.add(zzg, (Object) null);
        rh4Var.add(zzh, (Object) null);
        rh4Var.add(zzi, (Object) null);
        rh4Var.add(zzj, (Object) null);
        rh4Var.add(zzk, (Object) null);
        rh4Var.add(zzl, (Object) null);
        rh4Var.add(zzm, (Object) null);
        rh4Var.add(zzn, (Object) null);
        rh4Var.add(zzo, (Object) null);
        rh4Var.add(zzp, (Object) null);
        rh4Var.add(zzq, (Object) null);
        rh4Var.add(zzr, (Object) null);
        rh4Var.add(zzs, (Object) null);
        rh4Var.add(zzt, (Object) null);
        rh4Var.add(zzu, (Object) null);
        rh4Var.add(zzv, (Object) null);
        rh4Var.add(zzw, (Object) null);
        rh4Var.add(zzx, (Object) null);
        rh4Var.add(zzy, (Object) null);
        rh4Var.add(zzz, (Object) null);
        rh4Var.add(zzA, (Object) null);
        rh4Var.add(zzB, (Object) null);
        rh4Var.add(zzC, (Object) null);
        rh4Var.add(zzD, (Object) null);
        rh4Var.add(zzE, (Object) null);
        rh4Var.add(zzF, (Object) null);
        rh4Var.add(zzG, (Object) null);
        rh4Var.add(zzH, (Object) null);
        rh4Var.add(zzI, (Object) null);
        rh4Var.add(zzJ, (Object) null);
        rh4Var.add(zzK, (Object) null);
        rh4Var.add(zzL, (Object) null);
        rh4Var.add(zzM, (Object) null);
        rh4Var.add(zzN, zzmyVar.zzb());
        rh4Var.add(zzO, zzmyVar.zza());
        rh4Var.add(zzP, (Object) null);
        rh4Var.add(zzQ, (Object) null);
        rh4Var.add(zzR, (Object) null);
        rh4Var.add(zzS, (Object) null);
        rh4Var.add(zzT, (Object) null);
        rh4Var.add(zzU, (Object) null);
        rh4Var.add(zzV, (Object) null);
        rh4Var.add(zzW, (Object) null);
        rh4Var.add(zzX, (Object) null);
        rh4Var.add(zzY, (Object) null);
        rh4Var.add(zzZ, (Object) null);
        rh4Var.add(zzaa, (Object) null);
        rh4Var.add(zzab, zzmyVar.zzc());
        rh4Var.add(zzac, (Object) null);
        rh4Var.add(zzad, (Object) null);
        rh4Var.add(zzae, (Object) null);
        rh4Var.add(zzaf, (Object) null);
        rh4Var.add(zzag, (Object) null);
        rh4Var.add(zzah, (Object) null);
        rh4Var.add(zzai, (Object) null);
        rh4Var.add(zzaj, (Object) null);
        rh4Var.add(zzak, (Object) null);
        rh4Var.add(zzal, (Object) null);
        rh4Var.add(zzam, (Object) null);
        rh4Var.add(zzan, (Object) null);
        rh4Var.add(zzao, (Object) null);
        rh4Var.add(zzap, (Object) null);
        rh4Var.add(zzaq, (Object) null);
        rh4Var.add(zzar, (Object) null);
        rh4Var.add(zzas, (Object) null);
        rh4Var.add(zzat, (Object) null);
        rh4Var.add(zzau, (Object) null);
        rh4Var.add(zzav, (Object) null);
        rh4Var.add(zzaw, (Object) null);
        rh4Var.add(zzax, (Object) null);
        rh4Var.add(zzay, (Object) null);
        rh4Var.add(zzaz, (Object) null);
        rh4Var.add(zzaA, (Object) null);
        rh4Var.add(zzaB, (Object) null);
        rh4Var.add(zzaC, (Object) null);
        rh4Var.add(zzaD, (Object) null);
        rh4Var.add(zzaE, (Object) null);
        rh4Var.add(zzaF, (Object) null);
        rh4Var.add(zzaG, (Object) null);
        rh4Var.add(zzaH, (Object) null);
        rh4Var.add(zzaI, (Object) null);
        rh4Var.add(zzaJ, (Object) null);
        rh4Var.add(zzaK, (Object) null);
        rh4Var.add(zzaL, (Object) null);
        rh4Var.add(zzaM, (Object) null);
        rh4Var.add(zzaN, (Object) null);
        rh4Var.add(zzaO, (Object) null);
        rh4Var.add(zzaP, (Object) null);
        rh4Var.add(zzaQ, (Object) null);
        rh4Var.add(zzaR, (Object) null);
        rh4Var.add(zzaS, (Object) null);
        rh4Var.add(zzaT, (Object) null);
        rh4Var.add(zzaU, (Object) null);
        rh4Var.add(zzaV, (Object) null);
        rh4Var.add(zzaW, (Object) null);
        rh4Var.add(zzaX, (Object) null);
        rh4Var.add(zzaY, (Object) null);
        rh4Var.add(zzaZ, (Object) null);
        rh4Var.add(zzba, (Object) null);
        rh4Var.add(zzbb, (Object) null);
        rh4Var.add(zzbc, (Object) null);
        rh4Var.add(zzbd, (Object) null);
        rh4Var.add(zzbe, (Object) null);
        rh4Var.add(zzbf, (Object) null);
        rh4Var.add(zzbg, (Object) null);
        rh4Var.add(zzbh, (Object) null);
        rh4Var.add(zzbi, (Object) null);
        rh4Var.add(zzbj, (Object) null);
        rh4Var.add(zzbk, (Object) null);
        rh4Var.add(zzbl, (Object) null);
        rh4Var.add(zzbm, (Object) null);
        rh4Var.add(zzbn, (Object) null);
        rh4Var.add(zzbo, (Object) null);
        rh4Var.add(zzbp, (Object) null);
        rh4Var.add(zzbq, (Object) null);
        rh4Var.add(zzbr, (Object) null);
        rh4Var.add(zzbs, (Object) null);
        rh4Var.add(zzbt, (Object) null);
        rh4Var.add(zzbu, (Object) null);
        rh4Var.add(zzbv, (Object) null);
        rh4Var.add(zzbw, (Object) null);
        rh4Var.add(zzbx, (Object) null);
        rh4Var.add(zzby, (Object) null);
    }
}
