<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <AssemblyTitle>STORM DSi Decryptor 1.1.2</AssemblyTitle>
    <Product>STORM DSi Decryptor 1.1.2</Product>
    <Title>STORM DSi Decryptor 1.1.2</Title>
    <Description>STORM DSi Decryptor 1.1.2</Description>
    <Company>STORM SOFT</Company>
    <Authors>ReiKatari</Authors>
    <Copyright>Copyright © 2026 STORM TEAM</Copyright>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload\STORM DSi Decryptor.exe" Link="Payload\STORM DSi Decryptor.exe" />
    <EmbeddedResource Include="Payload\Быстрая_Расшифровка_Игр.bat" Link="Payload\Быстрая_Расшифровка_Игр.bat" />
    <EmbeddedResource Include="Resources\AppIcon.ico" Link="Resources\AppIcon.ico" />
    <EmbeddedResource Include="Resources\logo.png" Link="Resources\logo.png" />
    <EmbeddedResource Include="Resources\STORM_Certificate.cer" Link="Resources\STORM_Certificate.cer" />
  </ItemGroup>

</Project>
