package defpackage;

import android.view.ViewGroup;
import androidx.recyclerview.widget.RecyclerView;
import java.util.HashMap;
/* compiled from: r8-map-id-497bfa0f37aff44fe2e52f5de82fa8e9b472cf58d62eb3c7b7ed26472aaf487a */
/* renamed from: py0  reason: default package */
/* loaded from: classes.dex */
public final class py0 {
    public int a;
    public String b;
    public final sy0 c;
    public final ry0 d;
    public final qy0 e;
    public final ty0 f;
    public HashMap g;
    public oy0 h;

    /* JADX WARN: Type inference failed for: r0v0, types: [java.lang.Object, sy0] */
    /* JADX WARN: Type inference failed for: r0v1, types: [ry0, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v2, types: [qy0, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v3, types: [java.lang.Object, ty0] */
    public py0() {
        ?? obj = new Object();
        obj.a = false;
        obj.b = 0;
        obj.c = 0;
        obj.d = 1.0f;
        obj.e = Float.NaN;
        this.c = obj;
        ?? obj2 = new Object();
        obj2.a = false;
        obj2.b = -1;
        obj2.c = 0;
        obj2.d = null;
        obj2.e = -1;
        obj2.f = 0;
        obj2.g = Float.NaN;
        obj2.h = Float.NaN;
        obj2.i = Float.NaN;
        obj2.j = -1;
        obj2.k = null;
        obj2.l = -3;
        obj2.m = -1;
        this.d = obj2;
        ?? obj3 = new Object();
        obj3.a = false;
        obj3.b = false;
        obj3.e = -1;
        obj3.f = -1;
        obj3.g = -1.0f;
        obj3.h = true;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = -1;
        obj3.w = -1;
        obj3.x = 0.5f;
        obj3.y = 0.5f;
        obj3.z = null;
        obj3.A = -1;
        obj3.B = 0;
        obj3.C = RecyclerView.A1;
        obj3.D = -1;
        obj3.E = -1;
        obj3.F = -1;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = 0;
        obj3.M = 0;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = Integer.MIN_VALUE;
        obj3.T = Integer.MIN_VALUE;
        obj3.U = -1.0f;
        obj3.V = -1.0f;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = 0;
        obj3.Z = 0;
        obj3.a0 = 0;
        obj3.b0 = 0;
        obj3.c0 = 0;
        obj3.d0 = 0;
        obj3.e0 = 1.0f;
        obj3.f0 = 1.0f;
        obj3.g0 = -1;
        obj3.h0 = 0;
        obj3.i0 = -1;
        obj3.m0 = false;
        obj3.n0 = false;
        obj3.o0 = true;
        obj3.p0 = 0;
        this.e = obj3;
        ?? obj4 = new Object();
        obj4.a = false;
        obj4.b = RecyclerView.A1;
        obj4.c = RecyclerView.A1;
        obj4.d = RecyclerView.A1;
        obj4.e = 1.0f;
        obj4.f = 1.0f;
        obj4.g = Float.NaN;
        obj4.h = Float.NaN;
        obj4.i = -1;
        obj4.j = RecyclerView.A1;
        obj4.k = RecyclerView.A1;
        obj4.l = RecyclerView.A1;
        obj4.m = false;
        obj4.n = RecyclerView.A1;
        this.f = obj4;
        this.g = new HashMap();
    }

    public static void a(py0 py0Var, int i, jy0 jy0Var) {
        py0Var.a = i;
        qy0 qy0Var = py0Var.e;
        qy0Var.i = jy0Var.e;
        qy0Var.j = jy0Var.f;
        qy0Var.k = jy0Var.g;
        qy0Var.l = jy0Var.h;
        qy0Var.m = jy0Var.i;
        qy0Var.n = jy0Var.j;
        qy0Var.o = jy0Var.k;
        qy0Var.p = jy0Var.l;
        qy0Var.q = jy0Var.m;
        qy0Var.r = jy0Var.n;
        qy0Var.s = jy0Var.o;
        qy0Var.t = jy0Var.s;
        qy0Var.u = jy0Var.t;
        qy0Var.v = jy0Var.u;
        qy0Var.w = jy0Var.v;
        qy0Var.x = jy0Var.E;
        qy0Var.y = jy0Var.F;
        qy0Var.z = jy0Var.G;
        qy0Var.A = jy0Var.p;
        qy0Var.B = jy0Var.q;
        qy0Var.C = jy0Var.r;
        qy0Var.D = jy0Var.T;
        qy0Var.E = jy0Var.U;
        qy0Var.F = jy0Var.V;
        qy0Var.g = jy0Var.c;
        qy0Var.e = jy0Var.a;
        qy0Var.f = jy0Var.b;
        qy0Var.c = ((ViewGroup.MarginLayoutParams) jy0Var).width;
        qy0Var.d = ((ViewGroup.MarginLayoutParams) jy0Var).height;
        qy0Var.G = ((ViewGroup.MarginLayoutParams) jy0Var).leftMargin;
        qy0Var.H = ((ViewGroup.MarginLayoutParams) jy0Var).rightMargin;
        qy0Var.I = ((ViewGroup.MarginLayoutParams) jy0Var).topMargin;
        qy0Var.J = ((ViewGroup.MarginLayoutParams) jy0Var).bottomMargin;
        qy0Var.M = jy0Var.D;
        qy0Var.U = jy0Var.I;
        qy0Var.V = jy0Var.H;
        qy0Var.X = jy0Var.K;
        qy0Var.W = jy0Var.J;
        qy0Var.m0 = jy0Var.W;
        qy0Var.n0 = jy0Var.X;
        qy0Var.Y = jy0Var.L;
        qy0Var.Z = jy0Var.M;
        qy0Var.a0 = jy0Var.P;
        qy0Var.b0 = jy0Var.Q;
        qy0Var.c0 = jy0Var.N;
        qy0Var.d0 = jy0Var.O;
        qy0Var.e0 = jy0Var.R;
        qy0Var.f0 = jy0Var.S;
        qy0Var.l0 = jy0Var.Y;
        qy0Var.O = jy0Var.x;
        qy0Var.Q = jy0Var.z;
        qy0Var.N = jy0Var.w;
        qy0Var.P = jy0Var.y;
        qy0Var.S = jy0Var.A;
        qy0Var.R = jy0Var.B;
        qy0Var.T = jy0Var.C;
        qy0Var.p0 = jy0Var.Z;
        qy0Var.K = jy0Var.getMarginEnd();
        qy0Var.L = jy0Var.getMarginStart();
    }

    public final void b(jy0 jy0Var) {
        qy0 qy0Var = this.e;
        jy0Var.e = qy0Var.i;
        jy0Var.f = qy0Var.j;
        jy0Var.g = qy0Var.k;
        jy0Var.h = qy0Var.l;
        jy0Var.i = qy0Var.m;
        jy0Var.j = qy0Var.n;
        jy0Var.k = qy0Var.o;
        jy0Var.l = qy0Var.p;
        jy0Var.m = qy0Var.q;
        jy0Var.n = qy0Var.r;
        jy0Var.o = qy0Var.s;
        jy0Var.s = qy0Var.t;
        jy0Var.t = qy0Var.u;
        jy0Var.u = qy0Var.v;
        jy0Var.v = qy0Var.w;
        ((ViewGroup.MarginLayoutParams) jy0Var).leftMargin = qy0Var.G;
        ((ViewGroup.MarginLayoutParams) jy0Var).rightMargin = qy0Var.H;
        ((ViewGroup.MarginLayoutParams) jy0Var).topMargin = qy0Var.I;
        ((ViewGroup.MarginLayoutParams) jy0Var).bottomMargin = qy0Var.J;
        jy0Var.A = qy0Var.S;
        jy0Var.B = qy0Var.R;
        jy0Var.x = qy0Var.O;
        jy0Var.z = qy0Var.Q;
        jy0Var.E = qy0Var.x;
        jy0Var.F = qy0Var.y;
        jy0Var.p = qy0Var.A;
        jy0Var.q = qy0Var.B;
        jy0Var.r = qy0Var.C;
        jy0Var.G = qy0Var.z;
        jy0Var.T = qy0Var.D;
        jy0Var.U = qy0Var.E;
        jy0Var.I = qy0Var.U;
        jy0Var.H = qy0Var.V;
        jy0Var.K = qy0Var.X;
        jy0Var.J = qy0Var.W;
        jy0Var.W = qy0Var.m0;
        jy0Var.X = qy0Var.n0;
        jy0Var.L = qy0Var.Y;
        jy0Var.M = qy0Var.Z;
        jy0Var.P = qy0Var.a0;
        jy0Var.Q = qy0Var.b0;
        jy0Var.N = qy0Var.c0;
        jy0Var.O = qy0Var.d0;
        jy0Var.R = qy0Var.e0;
        jy0Var.S = qy0Var.f0;
        jy0Var.V = qy0Var.F;
        jy0Var.c = qy0Var.g;
        jy0Var.a = qy0Var.e;
        jy0Var.b = qy0Var.f;
        ((ViewGroup.MarginLayoutParams) jy0Var).width = qy0Var.c;
        ((ViewGroup.MarginLayoutParams) jy0Var).height = qy0Var.d;
        String str = qy0Var.l0;
        if (str != null) {
            jy0Var.Y = str;
        }
        jy0Var.Z = qy0Var.p0;
        jy0Var.setMarginStart(qy0Var.L);
        jy0Var.setMarginEnd(qy0Var.K);
        jy0Var.a();
    }

    /* renamed from: c */
    public final py0 clone() {
        py0 py0Var = new py0();
        py0Var.e.a(this.e);
        py0Var.d.a(this.d);
        sy0 sy0Var = this.c;
        boolean z = sy0Var.a;
        sy0 sy0Var2 = py0Var.c;
        sy0Var2.a = z;
        sy0Var2.b = sy0Var.b;
        sy0Var2.d = sy0Var.d;
        sy0Var2.e = sy0Var.e;
        sy0Var2.c = sy0Var.c;
        py0Var.f.a(this.f);
        py0Var.a = this.a;
        py0Var.h = this.h;
        return py0Var;
    }
}
