package defpackage;

import java.util.List;
/* compiled from: r8-map-id-497bfa0f37aff44fe2e52f5de82fa8e9b472cf58d62eb3c7b7ed26472aaf487a */
/* renamed from: rr1  reason: default package */
/* loaded from: classes.dex */
public abstract class rr1 {
    public static final List a = l07.c0(new u95(-1, "Native compMode - keep packed control plane"), new u95(0, "compMode 0 - sample 3D path, normal composite branch"), new u95(1, "compMode 1 - 3D-aware branch with direct 2D/3D selection"), new u95(2, "compMode 2 - 3D-aware blend branch"), new u95(3, "compMode 3 - 3D-aware alternate blend branch"), new u95(4, "compMode 4 - capture-backed 3D placeholder branch"), new u95(5, "compMode 5 - reserved/debug passthrough branch"), new u95(6, "compMode 6 - reserved/debug passthrough branch"), new u95(7, "compMode 7 - no live 3D sample unless temporal fallback is marked"));
    public static final List b = l07.c0(new t95("BG0 - first static or 3D background layer", 0, "Nintendo DS BG0. Code gate: DISPCNT bit 8; DrawBG_Text, or DrawBG_3D on Engine A when DISPCNT bit 3 selects the 3D background."), new t95("BG1 - static background layer", 1, "Nintendo DS BG1. Code gate: DISPCNT bit 9; currently routes through DrawBG_Text in the software 2D compositor."), new t95("BG2 - static, affine, affine extended or large screen background", 2, "Nintendo DS BG2. Code gate: DISPCNT bit 10; routes through DrawBG_Text, DrawBG_Affine, DrawBG_Extended or DrawBG_Large depending on BG mode and BGCNT."), new t95("BG3 - static, affine or affine extended background", 3, "Nintendo DS BG3. Code gate: DISPCNT bit 11; routes through DrawBG_Text, DrawBG_Affine or DrawBG_Extended depending on BG mode and BGCNT."));
    public static final List c = l07.c0(new y95("Priority 0 - frontmost", 0, "Highest Nintendo DS priority; this layer is drawn closest to the viewer."), new y95("Priority 1", 1, "Second-highest Nintendo DS priority."), new y95("Priority 2", 2, "Second-lowest Nintendo DS priority."), new y95("Priority 3 - backmost", 3, "Lowest Nintendo DS priority; this layer is drawn furthest back."));
    public static final List d = l07.c0(new x95("OBJ OAM index 0..31 - frontmost order bucket", 0, "OAM entries 0-31. Code gate: `sprnum / 32` in `DrawSprites`; lower OBJ indices are drawn later for equal priority and usually appear in front."), new x95("OBJ OAM index 32..63", 1, "OAM entries 32-63. Code gate: `sprnum / 32` in `DrawSprites`; useful for separating grouped composite sprites with the same OBJ priority."), new x95("OBJ OAM index 64..95", 2, "OAM entries 64-95. Code gate: `sprnum / 32` in `DrawSprites`; later than 96-127 but behind lower OAM index buckets at equal priority."), new x95("OBJ OAM index 96..127 - backmost order bucket", 3, "OAM entries 96-127. Code gate: `sprnum / 32` in `DrawSprites`; highest OBJ indices are drawn first for equal priority and usually sit furthest back."));
}
