using System;
using System.Collections.Generic;

namespace StormDsiDecryptor;

public static class LocalizationManager
{
    public static string CurrentLanguage { get; set; } = "ru";

    private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
    {
        ["ru"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "Сверхбыстрая утилита расшифровки Modcrypt для Nintendo DSi и DSiWare",
            ["DragDropHint"] = "Перетащите сюда файлы .nds, .dsi, .app или целую папку с играми",
            ["AddFiles"] = "Добавить файлы",
            ["AddFolder"] = "Добавить папку",
            ["DecryptAll"] = "Расшифровать все",
            ["ClearList"] = "Очистить список",
            ["OpenFolder"] = "Открыть папку",
            ["ColFileName"] = "Имя файла",
            ["ColTitle"] = "Название игры",
            ["ColCode"] = "Код",
            ["ColSize"] = "Размер",
            ["ColStatus"] = "Статус",
            ["StatusEncrypted"] = "Зашифрован (Modcrypt)",
            ["StatusDecrypted"] = "Расшифрован (Готов)",
            ["StatusNotDsi"] = "Обычный DS (Без шифрования)",
            ["StatusProcessing"] = "Расшифровка...",
            ["StatusSuccess"] = "Успешно расшифрован",
            ["StatusFailed"] = "Ошибка расшифровки",
            ["StatusCopied"] = "Скопирован (Готов)",
            ["StatusCopying"] = "Копирование...",
            ["StatusCopyFailed"] = "Ошибка копирования",
            ["StatusNeedsPatch"] = "Требуется патч",
            ["StatusPatching"] = "Патчинг совместимости...",
            ["StatusPatched"] = "Пропатчен (Готов)",
            ["ModeCopy"] = "Создавать копию",
            ["ModeInPlace"] = "Перезаписывать оригиналы на месте",
            ["TotalGames"] = "Всего игр",
            ["EncryptedCount"] = "Требуют расшифровки",
            ["DecryptedCount"] = "Готово к запуску",
            ["LogTitle"] = "Журнал операций",
            ["ThemeLabel"] = "Тема оформления",
            ["LangLabel"] = "Язык интерфейса",
            ["MenuDeleteSelected"] = "Удалить выбранное (DEL)",
            ["MenuClearAll"] = "Очистить весь список",
            ["AllDone"] = "Все выбранные игры успешно расшифрованы и готовы к запуску!",
            ["TabQueue"] = "Очередь обработки",
            ["TabHistory"] = "История операций",
            ["HistoryEmpty"] = "История операций пуста",
            ["ClearHistory"] = "Очистить историю",
            ["ConfirmClearHistory"] = "Вы действительно хотите удалить всю историю операций?",
            ["ColProcessedAt"] = "Дата обработки",
            ["DuplicateTitle"] = "Игра уже обрабатывалась",
            ["DuplicateMsg"] = "Данная игра уже была успешно обработана ранее. Хотите отменить операцию или обработать её заново?",
            ["BtnSkip"] = "Пропустить",
            ["BtnReprocess"] = "Обработать заново",
            ["ChkApplyToAllDuplicates"] = "Применить ко всем повторным играм",
            ["ShowInExplorer"] = "Показать в проводнике",
            ["OutputFolderLabel"] = "Папка сохранения:",
            ["OutputFolderDefault"] = "Выберите папку для сохранения копий...",
            ["BrowseFolder"] = "Обзор...",
            ["SelectOutputFolderTitle"] = "Выберите папку для сохранения копий",
            ["ResetOutputFolderTooltip"] = "Сбросить на папку по умолчанию"
        },
        ["en"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "Ultra-fast Modcrypt decryption utility for Nintendo DSi and DSiWare",
            ["DragDropHint"] = "Drag and drop .nds, .dsi, .app files or an entire folder here",
            ["AddFiles"] = "Add files",
            ["AddFolder"] = "Add folder",
            ["DecryptAll"] = "Decrypt all",
            ["ClearList"] = "Clear list",
            ["OpenFolder"] = "Open folder",
            ["ColFileName"] = "File name",
            ["ColTitle"] = "Game title",
            ["ColCode"] = "Code",
            ["ColSize"] = "Size",
            ["ColStatus"] = "Status",
            ["StatusEncrypted"] = "Encrypted (Modcrypt)",
            ["StatusDecrypted"] = "Decrypted (Ready)",
            ["StatusNotDsi"] = "Standard DS (No encryption)",
            ["StatusProcessing"] = "Decrypting...",
            ["StatusSuccess"] = "Successfully decrypted",
            ["StatusFailed"] = "Decryption error",
            ["StatusCopied"] = "Copied (Ready)",
            ["StatusCopying"] = "Copying...",
            ["StatusCopyFailed"] = "Copy failed",
            ["StatusNeedsPatch"] = "Patch required",
            ["StatusPatching"] = "Applying compatibility patch...",
            ["StatusPatched"] = "Patched (Ready)",
            ["ModeCopy"] = "Create copy",
            ["ModeInPlace"] = "Overwrite originals in-place",
            ["TotalGames"] = "Total games",
            ["EncryptedCount"] = "Need decryption",
            ["DecryptedCount"] = "Ready to play",
            ["LogTitle"] = "Operation log",
            ["ThemeLabel"] = "Visual theme",
            ["LangLabel"] = "Interface language",
            ["MenuDeleteSelected"] = "Delete selected (DEL)",
            ["MenuClearAll"] = "Clear entire list",
            ["AllDone"] = "All selected games have been successfully decrypted and are ready to run!",
            ["TabQueue"] = "Processing queue",
            ["TabHistory"] = "Operation history",
            ["HistoryEmpty"] = "Operation history is empty",
            ["ClearHistory"] = "Clear history",
            ["ConfirmClearHistory"] = "Are you sure you want to clear all operation history?",
            ["ColProcessedAt"] = "Processed date",
            ["DuplicateTitle"] = "Game already processed",
            ["DuplicateMsg"] = "This game was already processed earlier. Do you want to cancel or reprocess it?",
            ["BtnSkip"] = "Skip",
            ["BtnReprocess"] = "Reprocess",
            ["ChkApplyToAllDuplicates"] = "Apply to all duplicate games",
            ["ShowInExplorer"] = "Show in Explorer",
            ["OutputFolderLabel"] = "Save to folder:",
            ["OutputFolderDefault"] = "Select folder to save copies...",
            ["BrowseFolder"] = "Browse...",
            ["SelectOutputFolderTitle"] = "Select folder to save copies",
            ["ResetOutputFolderTooltip"] = "Reset to default folder"
        },
        ["de"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "Ultraschnelles Modcrypt-Entschlüsselungstool für Nintendo DSi und DSiWare",
            ["DragDropHint"] = "Ziehen Sie .nds-, .dsi-, .app-Dateien oder Ordner hierher",
            ["AddFiles"] = "Dateien hinzufügen",
            ["AddFolder"] = "Ordner hinzufügen",
            ["DecryptAll"] = "Alle entschlüsseln",
            ["ClearList"] = "Liste leeren",
            ["OpenFolder"] = "Ordner öffnen",
            ["ColFileName"] = "Dateiname",
            ["ColTitle"] = "Spieltitel",
            ["ColCode"] = "Code",
            ["ColSize"] = "Größe",
            ["ColStatus"] = "Status",
            ["StatusEncrypted"] = "Verschlüsselt (Modcrypt)",
            ["StatusDecrypted"] = "Entschlüsselt (Bereit)",
            ["StatusNotDsi"] = "Standard DS (Unverschlüsselt)",
            ["StatusProcessing"] = "Entschlüsselung...",
            ["StatusSuccess"] = "Erfolgreich entschlüsselt",
            ["StatusFailed"] = "Fehler bei der Entschlüsselung",
            ["StatusCopied"] = "Kopiert (Bereit)",
            ["StatusCopying"] = "Kopieren...",
            ["StatusCopyFailed"] = "Kopierfehler",
            ["StatusNeedsPatch"] = "Patch erforderlich",
            ["StatusPatching"] = "Kompatibilitätspatch anwenden...",
            ["StatusPatched"] = "Gepatcht (Bereit)",
            ["ModeCopy"] = "Kopie erstellen",
            ["ModeInPlace"] = "Originale direkt überschreiben",
            ["TotalGames"] = "Spiele gesamt",
            ["EncryptedCount"] = "Benötigen Entschlüsselung",
            ["DecryptedCount"] = "Bereit zum Start",
            ["LogTitle"] = "Protokoll",
            ["ThemeLabel"] = "Design",
            ["LangLabel"] = "Sprache",
            ["MenuDeleteSelected"] = "Ausgewählte löschen (DEL)",
            ["MenuClearAll"] = "Gesamte Liste leeren",
            ["AllDone"] = "Alle Spiele wurden erfolgreich entschlüsselt!",
            ["TabQueue"] = "Warteschlange",
            ["TabHistory"] = "Verlauf",
            ["HistoryEmpty"] = "Verlauf ist leer",
            ["ClearHistory"] = "Verlauf leeren",
            ["ConfirmClearHistory"] = "Möchten Sie den gesamten Verlauf wirklich löschen?",
            ["ColProcessedAt"] = "Bearbeitet am",
            ["DuplicateTitle"] = "Spiel bereits verarbeitet",
            ["DuplicateMsg"] = "Dieses Spiel wurde bereits verarbeitet. Möchten Sie abbrechen oder erneut verarbeiten?",
            ["BtnSkip"] = "Überspringen",
            ["BtnReprocess"] = "Erneut verarbeiten",
            ["ChkApplyToAllDuplicates"] = "Auf alle Duplikate anwenden",
            ["ShowInExplorer"] = "Im Explorer anzeigen",
            ["OutputFolderLabel"] = "Zielordner:",
            ["OutputFolderDefault"] = "Ordner zum Speichern von Kopien auswählen...",
            ["BrowseFolder"] = "Durchsuchen...",
            ["SelectOutputFolderTitle"] = "Ordner zum Speichern von Kopien auswählen",
            ["ResetOutputFolderTooltip"] = "Auf Standardordner zurücksetzen"
        },
        ["fr"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "Utilitaire de déchiffrement Modcrypt ultra-rapide pour Nintendo DSi et DSiWare",
            ["DragDropHint"] = "Glissez-déposez des fichiers .nds, .dsi, .app ou un dossier ici",
            ["AddFiles"] = "Ajouter des fichiers",
            ["AddFolder"] = "Ajouter un dossier",
            ["DecryptAll"] = "Tout déchiffrer",
            ["ClearList"] = "Effacer la liste",
            ["OpenFolder"] = "Ouvrir le dossier",
            ["ColFileName"] = "Nom de fichier",
            ["ColTitle"] = "Titre du jeu",
            ["ColCode"] = "Code",
            ["ColSize"] = "Taille",
            ["ColStatus"] = "Statut",
            ["StatusEncrypted"] = "Chiffré (Modcrypt)",
            ["StatusDecrypted"] = "Déchiffré (Prêt)",
            ["StatusNotDsi"] = "DS standard (Non chiffré)",
            ["StatusProcessing"] = "Déchiffrement...",
            ["StatusSuccess"] = "Déchiffré avec succès",
            ["StatusFailed"] = "Erreur de déchiffrement",
            ["StatusCopied"] = "Copié (Prêt)",
            ["StatusCopying"] = "Copie en cours...",
            ["StatusCopyFailed"] = "Échec de la copie",
            ["StatusNeedsPatch"] = "Patch requis",
            ["StatusPatching"] = "Application du patch de compatibilité...",
            ["StatusPatched"] = "Patché (Prêt)",
            ["ModeCopy"] = "Créer une copie",
            ["ModeInPlace"] = "Écraser les originaux sur place",
            ["TotalGames"] = "Total des jeux",
            ["EncryptedCount"] = "À déchiffrer",
            ["DecryptedCount"] = "Prêt à jouer",
            ["LogTitle"] = "Journal",
            ["ThemeLabel"] = "Thème",
            ["LangLabel"] = "Langue",
            ["MenuDeleteSelected"] = "Supprimer la sélection (DEL)",
            ["MenuClearAll"] = "Effacer toute la liste",
            ["AllDone"] = "Tous les jeux ont été décryptés avec succès!",
            ["TabQueue"] = "File de traitement",
            ["TabHistory"] = "Historique",
            ["HistoryEmpty"] = "L'historique est vide",
            ["ClearHistory"] = "Effacer l'historique",
            ["ConfirmClearHistory"] = "Voulez-vous vraiment effacer tout l'historique?",
            ["ColProcessedAt"] = "Date de traitement",
            ["DuplicateTitle"] = "Jeu déjà traité",
            ["DuplicateMsg"] = "Ce jeu a déjà été traité. Voulez-vous annuler ou retraiter?",
            ["BtnSkip"] = "Ignorer",
            ["BtnReprocess"] = "Retraiter",
            ["ChkApplyToAllDuplicates"] = "Appliquer à tous les doublons",
            ["ShowInExplorer"] = "Afficher dans l'Explorateur",
            ["OutputFolderLabel"] = "Dossier de sortie :",
            ["OutputFolderDefault"] = "Sélectionnez un dossier pour enregistrer les copies...",
            ["BrowseFolder"] = "Parcourir...",
            ["SelectOutputFolderTitle"] = "Sélectionnez un dossier pour enregistrer les copies",
            ["ResetOutputFolderTooltip"] = "Réinitialiser au dossier par défaut"
        },
        ["zh"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "适用于 Nintendo DSi 和 DSiWare 的极速 Modcrypt 解密工具",
            ["DragDropHint"] = "将 .nds、.dsi、.app 文件或游戏文件夹拖放至此处",
            ["AddFiles"] = "添加文件",
            ["AddFolder"] = "添加文件夹",
            ["DecryptAll"] = "解密全部",
            ["ClearList"] = "清空列表",
            ["OpenFolder"] = "打开文件夹",
            ["ColFileName"] = "文件名",
            ["ColTitle"] = "游戏名称",
            ["ColCode"] = "代码",
            ["ColSize"] = "大小",
            ["ColStatus"] = "状态",
            ["StatusEncrypted"] = "已加密 (Modcrypt)",
            ["StatusDecrypted"] = "已解密 (就绪)",
            ["StatusNotDsi"] = "标准 DS (未加密)",
            ["StatusProcessing"] = "正在解密...",
            ["StatusSuccess"] = "解密成功",
            ["StatusFailed"] = "解密失败",
            ["StatusCopied"] = "已复制（就绪）",
            ["StatusCopying"] = "正在复制...",
            ["StatusCopyFailed"] = "复制失败",
            ["StatusNeedsPatch"] = "需要补丁",
            ["StatusPatching"] = "正在应用兼容性补丁...",
            ["StatusPatched"] = "已修补（就绪）",
            ["ModeCopy"] = "创建副本",
            ["ModeInPlace"] = "直接就地覆盖原文件",
            ["TotalGames"] = "游戏总数",
            ["EncryptedCount"] = "待解密",
            ["DecryptedCount"] = "可运行",
            ["LogTitle"] = "操作日志",
            ["ThemeLabel"] = "界面主题",
            ["LangLabel"] = "显示语言",
            ["MenuDeleteSelected"] = "删除所选项目 (DEL)",
            ["MenuClearAll"] = "清空整个列表",
            ["AllDone"] = "所有选定游戏已成功解密，可直接运行！",
            ["TabQueue"] = "处理队列",
            ["TabHistory"] = "操作历史",
            ["HistoryEmpty"] = "操作历史为空",
            ["ClearHistory"] = "清空历史",
            ["ConfirmClearHistory"] = "确定要清空所有操作历史吗？",
            ["ColProcessedAt"] = "处理时间",
            ["DuplicateTitle"] = "游戏已处理过",
            ["DuplicateMsg"] = "此游戏之前已被处理。您想取消操作还是重新处理？",
            ["BtnSkip"] = "跳过",
            ["BtnReprocess"] = "重新处理",
            ["ChkApplyToAllDuplicates"] = "应用到所有重复项",
            ["ShowInExplorer"] = "在资源管理器中显示",
            ["OutputFolderLabel"] = "输出目录：",
            ["OutputFolderDefault"] = "选择保存副本的文件夹...",
            ["BrowseFolder"] = "浏览...",
            ["SelectOutputFolderTitle"] = "选择保存副本的文件夹",
            ["ResetOutputFolderTooltip"] = "重置为默认文件夹"
        },
        ["ja"] = new()
        {
            ["AppTitle"] = "STORM DSi Decryptor",
            ["Subtitle"] = "Nintendo DSi および DSiWare 用の超高速 Modcrypt 復号ユーティリティ",
            ["DragDropHint"] = "ここに .nds、.dsi、.app ファイルまたはフォルダをドラッグ＆ドロップ",
            ["AddFiles"] = "ファイル追加",
            ["AddFolder"] = "フォルダ追加",
            ["DecryptAll"] = "すべて復号",
            ["ClearList"] = "リストをクリア",
            ["OpenFolder"] = "フォルダを開く",
            ["ColFileName"] = "ファイル名",
            ["ColTitle"] = "ゲーム名",
            ["ColCode"] = "コード",
            ["ColSize"] = "サイズ",
            ["ColStatus"] = "ステータス",
            ["StatusEncrypted"] = "暗号化済み (Modcrypt)",
            ["StatusDecrypted"] = "復号済み (準備完了)",
            ["StatusNotDsi"] = "標準 DS (暗号化なし)",
            ["StatusProcessing"] = "復号処理中...",
            ["StatusSuccess"] = "復号完了",
            ["StatusFailed"] = "復号エラー",
            ["StatusCopied"] = "コピー完了（準備完了）",
            ["StatusCopying"] = "コピー中...",
            ["StatusCopyFailed"] = "コピー失敗",
            ["StatusNeedsPatch"] = "パッチが必要",
            ["StatusPatching"] = "互換性パッチを適用中...",
            ["StatusPatched"] = "パッチ適用完了（準備完了）",
            ["ModeCopy"] = "コピーを作成",
            ["ModeInPlace"] = "元のファイルを上書き",
            ["TotalGames"] = "ゲーム総数",
            ["EncryptedCount"] = "要復号",
            ["DecryptedCount"] = "起動可能",
            ["LogTitle"] = "操作ログ",
            ["ThemeLabel"] = "テーマ",
            ["LangLabel"] = "言語",
            ["MenuDeleteSelected"] = "選択項目を削除 (DEL)",
            ["MenuClearAll"] = "リスト全体をクリア",
            ["AllDone"] = "選択されたすべてのゲームが正常に復号されました！",
            ["TabQueue"] = "処理キュー",
            ["TabHistory"] = "操作履歴",
            ["HistoryEmpty"] = "操作履歴はありません",
            ["ClearHistory"] = "履歴をクリア",
            ["ConfirmClearHistory"] = "すべての操作履歴を削除してもよろしいですか？",
            ["ColProcessedAt"] = "処理日時",
            ["DuplicateTitle"] = "処理済みのゲーム",
            ["DuplicateMsg"] = "このゲームは以前に処理されています。キャンセルしますか、それとも再処理しますか？",
            ["BtnSkip"] = "スキップ",
            ["BtnReprocess"] = "再処理",
            ["ChkApplyToAllDuplicates"] = "すべての重複項目に適用",
            ["ShowInExplorer"] = "エクスプローラーで表示",
            ["OutputFolderLabel"] = "保存先フォルダ：",
            ["OutputFolderDefault"] = "コピー保存先フォルダを選択...",
            ["BrowseFolder"] = "参照...",
            ["SelectOutputFolderTitle"] = "コピー保存先フォルダを選択",
            ["ResetOutputFolderTooltip"] = "デフォルトフォルダにリセット"
        }
    };

    public static string Get(string key)
    {
        if (Strings.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var val))
        {
            return val;
        }
        if (Strings["ru"].TryGetValue(key, out var defaultVal))
        {
            return defaultVal;
        }
        return key;
    }
}
