<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <AssemblyName>STORM DSi Decryptor</AssemblyName>
    <RootNamespace>StormDsiDecryptor</RootNamespace>
    <Version>1.1.4</Version>
    <Authors>ReiKatari</Authors>
    <Company>STORM SOFT</Company>
    <Product>STORM DSi Decryptor</Product>
    <Description>Утилита сверхбыстрой расшифровки Modcrypt для Nintendo DSi и DSiWare</Description>
    <Copyright>Copyright © 2026 ReiKatari. All rights reserved.</Copyright>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Installer\**" />
    <None Remove="Installer\**" />
    <EmbeddedResource Remove="Installer\**" />
    <Resource Include="AppIcon.ico" />
  </ItemGroup>

</Project>
