package com.google.android.gms.internal.mlkit_vision_text_common;

import com.github.junrar.unpack.ppm.ModelPPM;
import com.google.mlkit.common.MlKitException;
import java.util.HashMap;
/* compiled from: r8-map-id-0dd4387375ec438f6a4c042bfe6cb4a3262713dcd4829883cccf19288831b1df */
/* loaded from: classes.dex */
final class zzio implements qh4 {
    private static final na2 zzA;
    private static final na2 zzB;
    private static final na2 zzC;
    private static final na2 zzD;
    private static final na2 zzE;
    private static final na2 zzF;
    private static final na2 zzG;
    private static final na2 zzH;
    private static final na2 zzI;
    private static final na2 zzJ;
    private static final na2 zzK;
    private static final na2 zzL;
    private static final na2 zzM;
    private static final na2 zzN;
    private static final na2 zzO;
    private static final na2 zzP;
    private static final na2 zzQ;
    private static final na2 zzR;
    private static final na2 zzS;
    private static final na2 zzT;
    private static final na2 zzU;
    private static final na2 zzV;
    private static final na2 zzW;
    private static final na2 zzX;
    private static final na2 zzY;
    private static final na2 zzZ;
    static final zzio zza = new zzio();
    private static final na2 zzaA;
    private static final na2 zzaB;
    private static final na2 zzaC;
    private static final na2 zzaD;
    private static final na2 zzaE;
    private static final na2 zzaF;
    private static final na2 zzaG;
    private static final na2 zzaH;
    private static final na2 zzaI;
    private static final na2 zzaJ;
    private static final na2 zzaK;
    private static final na2 zzaL;
    private static final na2 zzaM;
    private static final na2 zzaN;
    private static final na2 zzaO;
    private static final na2 zzaP;
    private static final na2 zzaQ;
    private static final na2 zzaR;
    private static final na2 zzaS;
    private static final na2 zzaT;
    private static final na2 zzaU;
    private static final na2 zzaV;
    private static final na2 zzaW;
    private static final na2 zzaX;
    private static final na2 zzaY;
    private static final na2 zzaZ;
    private static final na2 zzaa;
    private static final na2 zzab;
    private static final na2 zzac;
    private static final na2 zzad;
    private static final na2 zzae;
    private static final na2 zzaf;
    private static final na2 zzag;
    private static final na2 zzah;
    private static final na2 zzai;
    private static final na2 zzaj;
    private static final na2 zzak;
    private static final na2 zzal;
    private static final na2 zzam;
    private static final na2 zzan;
    private static final na2 zzao;
    private static final na2 zzap;
    private static final na2 zzaq;
    private static final na2 zzar;
    private static final na2 zzas;
    private static final na2 zzat;
    private static final na2 zzau;
    private static final na2 zzav;
    private static final na2 zzaw;
    private static final na2 zzax;
    private static final na2 zzay;
    private static final na2 zzaz;
    private static final na2 zzb;
    private static final na2 zzba;
    private static final na2 zzbb;
    private static final na2 zzbc;
    private static final na2 zzbd;
    private static final na2 zzbe;
    private static final na2 zzbf;
    private static final na2 zzbg;
    private static final na2 zzbh;
    private static final na2 zzbi;
    private static final na2 zzbj;
    private static final na2 zzbk;
    private static final na2 zzbl;
    private static final na2 zzbm;
    private static final na2 zzbn;
    private static final na2 zzbo;
    private static final na2 zzbp;
    private static final na2 zzbq;
    private static final na2 zzbr;
    private static final na2 zzbs;
    private static final na2 zzbt;
    private static final na2 zzbu;
    private static final na2 zzbv;
    private static final na2 zzbw;
    private static final na2 zzbx;
    private static final na2 zzby;
    private static final na2 zzc;
    private static final na2 zzd;
    private static final na2 zze;
    private static final na2 zzf;
    private static final na2 zzg;
    private static final na2 zzh;
    private static final na2 zzi;
    private static final na2 zzj;
    private static final na2 zzk;
    private static final na2 zzl;
    private static final na2 zzm;
    private static final na2 zzn;
    private static final na2 zzo;
    private static final na2 zzp;
    private static final na2 zzq;
    private static final na2 zzr;
    private static final na2 zzs;
    private static final na2 zzt;
    private static final na2 zzu;
    private static final na2 zzv;
    private static final na2 zzw;
    private static final na2 zzx;
    private static final na2 zzy;
    private static final na2 zzz;

    static {
        zzcx k = xg6.k(1);
        HashMap hashMap = new HashMap();
        hashMap.put(k.annotationType(), k);
        zzb = new na2("systemInfo", xg6.u(hashMap));
        zzcx k2 = xg6.k(2);
        HashMap hashMap2 = new HashMap();
        hashMap2.put(k2.annotationType(), k2);
        zzc = new na2("eventName", xg6.u(hashMap2));
        zzcx k3 = xg6.k(37);
        HashMap hashMap3 = new HashMap();
        hashMap3.put(k3.annotationType(), k3);
        zzd = new na2("isThickClient", xg6.u(hashMap3));
        zzcx k4 = xg6.k(61);
        HashMap hashMap4 = new HashMap();
        hashMap4.put(k4.annotationType(), k4);
        zze = new na2("clientType", xg6.u(hashMap4));
        zzcx k5 = xg6.k(3);
        HashMap hashMap5 = new HashMap();
        hashMap5.put(k5.annotationType(), k5);
        zzf = new na2("modelDownloadLogEvent", xg6.u(hashMap5));
        zzcx k6 = xg6.k(20);
        HashMap hashMap6 = new HashMap();
        hashMap6.put(k6.annotationType(), k6);
        zzg = new na2("customModelLoadLogEvent", xg6.u(hashMap6));
        zzcx k7 = xg6.k(4);
        HashMap hashMap7 = new HashMap();
        hashMap7.put(k7.annotationType(), k7);
        zzh = new na2("customModelInferenceLogEvent", xg6.u(hashMap7));
        zzcx k8 = xg6.k(29);
        HashMap hashMap8 = new HashMap();
        hashMap8.put(k8.annotationType(), k8);
        zzi = new na2("customModelCreateLogEvent", xg6.u(hashMap8));
        zzcx k9 = xg6.k(5);
        HashMap hashMap9 = new HashMap();
        hashMap9.put(k9.annotationType(), k9);
        zzj = new na2("onDeviceFaceDetectionLogEvent", xg6.u(hashMap9));
        zzcx k10 = xg6.k(59);
        HashMap hashMap10 = new HashMap();
        hashMap10.put(k10.annotationType(), k10);
        zzk = new na2("onDeviceFaceLoadLogEvent", xg6.u(hashMap10));
        zzcx k11 = xg6.k(6);
        HashMap hashMap11 = new HashMap();
        hashMap11.put(k11.annotationType(), k11);
        zzl = new na2("onDeviceTextDetectionLogEvent", xg6.u(hashMap11));
        zzcx k12 = xg6.k(79);
        HashMap hashMap12 = new HashMap();
        hashMap12.put(k12.annotationType(), k12);
        zzm = new na2("onDeviceTextDetectionLoadLogEvent", xg6.u(hashMap12));
        zzcx k13 = xg6.k(7);
        HashMap hashMap13 = new HashMap();
        hashMap13.put(k13.annotationType(), k13);
        zzn = new na2("onDeviceBarcodeDetectionLogEvent", xg6.u(hashMap13));
        zzcx k14 = xg6.k(58);
        HashMap hashMap14 = new HashMap();
        hashMap14.put(k14.annotationType(), k14);
        zzo = new na2("onDeviceBarcodeLoadLogEvent", xg6.u(hashMap14));
        zzcx k15 = xg6.k(48);
        HashMap hashMap15 = new HashMap();
        hashMap15.put(k15.annotationType(), k15);
        zzp = new na2("onDeviceImageLabelCreateLogEvent", xg6.u(hashMap15));
        zzcx k16 = xg6.k(49);
        HashMap hashMap16 = new HashMap();
        hashMap16.put(k16.annotationType(), k16);
        zzq = new na2("onDeviceImageLabelLoadLogEvent", xg6.u(hashMap16));
        zzcx k17 = xg6.k(18);
        HashMap hashMap17 = new HashMap();
        hashMap17.put(k17.annotationType(), k17);
        zzr = new na2("onDeviceImageLabelDetectionLogEvent", xg6.u(hashMap17));
        zzcx k18 = xg6.k(26);
        HashMap hashMap18 = new HashMap();
        hashMap18.put(k18.annotationType(), k18);
        zzs = new na2("onDeviceObjectCreateLogEvent", xg6.u(hashMap18));
        zzcx k19 = xg6.k(27);
        HashMap hashMap19 = new HashMap();
        hashMap19.put(k19.annotationType(), k19);
        zzt = new na2("onDeviceObjectLoadLogEvent", xg6.u(hashMap19));
        zzcx k20 = xg6.k(28);
        HashMap hashMap20 = new HashMap();
        hashMap20.put(k20.annotationType(), k20);
        zzu = new na2("onDeviceObjectInferenceLogEvent", xg6.u(hashMap20));
        zzcx k21 = xg6.k(44);
        HashMap hashMap21 = new HashMap();
        hashMap21.put(k21.annotationType(), k21);
        zzv = new na2("onDevicePoseDetectionLogEvent", xg6.u(hashMap21));
        zzcx k22 = xg6.k(45);
        HashMap hashMap22 = new HashMap();
        hashMap22.put(k22.annotationType(), k22);
        zzw = new na2("onDeviceSegmentationLogEvent", xg6.u(hashMap22));
        zzcx k23 = xg6.k(19);
        HashMap hashMap23 = new HashMap();
        hashMap23.put(k23.annotationType(), k23);
        zzx = new na2("onDeviceSmartReplyLogEvent", xg6.u(hashMap23));
        zzcx k24 = xg6.k(21);
        HashMap hashMap24 = new HashMap();
        hashMap24.put(k24.annotationType(), k24);
        zzy = new na2("onDeviceLanguageIdentificationLogEvent", xg6.u(hashMap24));
        zzcx k25 = xg6.k(22);
        HashMap hashMap25 = new HashMap();
        hashMap25.put(k25.annotationType(), k25);
        zzz = new na2("onDeviceTranslationLogEvent", xg6.u(hashMap25));
        zzcx k26 = xg6.k(8);
        HashMap hashMap26 = new HashMap();
        hashMap26.put(k26.annotationType(), k26);
        zzA = new na2("cloudFaceDetectionLogEvent", xg6.u(hashMap26));
        zzcx k27 = xg6.k(9);
        HashMap hashMap27 = new HashMap();
        hashMap27.put(k27.annotationType(), k27);
        zzB = new na2("cloudCropHintDetectionLogEvent", xg6.u(hashMap27));
        zzcx k28 = xg6.k(10);
        HashMap hashMap28 = new HashMap();
        hashMap28.put(k28.annotationType(), k28);
        zzC = new na2("cloudDocumentTextDetectionLogEvent", xg6.u(hashMap28));
        zzcx k29 = xg6.k(11);
        HashMap hashMap29 = new HashMap();
        hashMap29.put(k29.annotationType(), k29);
        zzD = new na2("cloudImagePropertiesDetectionLogEvent", xg6.u(hashMap29));
        zzcx k30 = xg6.k(12);
        HashMap hashMap30 = new HashMap();
        hashMap30.put(k30.annotationType(), k30);
        zzE = new na2("cloudImageLabelDetectionLogEvent", xg6.u(hashMap30));
        zzcx k31 = xg6.k(13);
        HashMap hashMap31 = new HashMap();
        hashMap31.put(k31.annotationType(), k31);
        zzF = new na2("cloudLandmarkDetectionLogEvent", xg6.u(hashMap31));
        zzcx k32 = xg6.k(14);
        HashMap hashMap32 = new HashMap();
        hashMap32.put(k32.annotationType(), k32);
        zzG = new na2("cloudLogoDetectionLogEvent", xg6.u(hashMap32));
        zzcx k33 = xg6.k(15);
        HashMap hashMap33 = new HashMap();
        hashMap33.put(k33.annotationType(), k33);
        zzH = new na2("cloudSafeSearchDetectionLogEvent", xg6.u(hashMap33));
        zzcx k34 = xg6.k(16);
        HashMap hashMap34 = new HashMap();
        hashMap34.put(k34.annotationType(), k34);
        zzI = new na2("cloudTextDetectionLogEvent", xg6.u(hashMap34));
        zzcx k35 = xg6.k(17);
        HashMap hashMap35 = new HashMap();
        hashMap35.put(k35.annotationType(), k35);
        zzJ = new na2("cloudWebSearchDetectionLogEvent", xg6.u(hashMap35));
        zzcx k36 = xg6.k(23);
        HashMap hashMap36 = new HashMap();
        hashMap36.put(k36.annotationType(), k36);
        zzK = new na2("automlImageLabelingCreateLogEvent", xg6.u(hashMap36));
        zzcx k37 = xg6.k(24);
        HashMap hashMap37 = new HashMap();
        hashMap37.put(k37.annotationType(), k37);
        zzL = new na2("automlImageLabelingLoadLogEvent", xg6.u(hashMap37));
        zzcx k38 = xg6.k(25);
        HashMap hashMap38 = new HashMap();
        hashMap38.put(k38.annotationType(), k38);
        zzM = new na2("automlImageLabelingInferenceLogEvent", xg6.u(hashMap38));
        zzcx k39 = xg6.k(39);
        HashMap hashMap39 = new HashMap();
        hashMap39.put(k39.annotationType(), k39);
        zzN = new na2("isModelDownloadedLogEvent", xg6.u(hashMap39));
        zzcx k40 = xg6.k(40);
        HashMap hashMap40 = new HashMap();
        hashMap40.put(k40.annotationType(), k40);
        zzO = new na2("deleteModelLogEvent", xg6.u(hashMap40));
        zzcx k41 = xg6.k(30);
        HashMap hashMap41 = new HashMap();
        hashMap41.put(k41.annotationType(), k41);
        zzP = new na2("aggregatedAutomlImageLabelingInferenceLogEvent", xg6.u(hashMap41));
        zzcx k42 = xg6.k(31);
        HashMap hashMap42 = new HashMap();
        hashMap42.put(k42.annotationType(), k42);
        zzQ = new na2("aggregatedCustomModelInferenceLogEvent", xg6.u(hashMap42));
        zzcx k43 = xg6.k(32);
        HashMap hashMap43 = new HashMap();
        hashMap43.put(k43.annotationType(), k43);
        zzR = new na2("aggregatedOnDeviceFaceDetectionLogEvent", xg6.u(hashMap43));
        zzcx k44 = xg6.k(33);
        HashMap hashMap44 = new HashMap();
        hashMap44.put(k44.annotationType(), k44);
        zzS = new na2("aggregatedOnDeviceBarcodeDetectionLogEvent", xg6.u(hashMap44));
        zzcx k45 = xg6.k(34);
        HashMap hashMap45 = new HashMap();
        hashMap45.put(k45.annotationType(), k45);
        zzT = new na2("aggregatedOnDeviceImageLabelDetectionLogEvent", xg6.u(hashMap45));
        zzcx k46 = xg6.k(35);
        HashMap hashMap46 = new HashMap();
        hashMap46.put(k46.annotationType(), k46);
        zzU = new na2("aggregatedOnDeviceObjectInferenceLogEvent", xg6.u(hashMap46));
        zzcx k47 = xg6.k(36);
        HashMap hashMap47 = new HashMap();
        hashMap47.put(k47.annotationType(), k47);
        zzV = new na2("aggregatedOnDeviceTextDetectionLogEvent", xg6.u(hashMap47));
        zzcx k48 = xg6.k(46);
        HashMap hashMap48 = new HashMap();
        hashMap48.put(k48.annotationType(), k48);
        zzW = new na2("aggregatedOnDevicePoseDetectionLogEvent", xg6.u(hashMap48));
        zzcx k49 = xg6.k(47);
        HashMap hashMap49 = new HashMap();
        hashMap49.put(k49.annotationType(), k49);
        zzX = new na2("aggregatedOnDeviceSegmentationLogEvent", xg6.u(hashMap49));
        zzcx k50 = xg6.k(69);
        HashMap hashMap50 = new HashMap();
        hashMap50.put(k50.annotationType(), k50);
        zzY = new na2("pipelineAccelerationInferenceEvents", xg6.u(hashMap50));
        zzcx k51 = xg6.k(42);
        HashMap hashMap51 = new HashMap();
        hashMap51.put(k51.annotationType(), k51);
        zzZ = new na2("remoteConfigLogEvent", xg6.u(hashMap51));
        zzcx k52 = xg6.k(50);
        HashMap hashMap52 = new HashMap();
        hashMap52.put(k52.annotationType(), k52);
        zzaa = new na2("inputImageConstructionLogEvent", xg6.u(hashMap52));
        zzcx k53 = xg6.k(51);
        HashMap hashMap53 = new HashMap();
        hashMap53.put(k53.annotationType(), k53);
        zzab = new na2("leakedHandleEvent", xg6.u(hashMap53));
        zzcx k54 = xg6.k(52);
        HashMap hashMap54 = new HashMap();
        hashMap54.put(k54.annotationType(), k54);
        zzac = new na2("cameraSourceLogEvent", xg6.u(hashMap54));
        zzcx k55 = xg6.k(53);
        HashMap hashMap55 = new HashMap();
        hashMap55.put(k55.annotationType(), k55);
        zzad = new na2("imageLabelOptionalModuleLogEvent", xg6.u(hashMap55));
        zzcx k56 = xg6.k(54);
        HashMap hashMap56 = new HashMap();
        hashMap56.put(k56.annotationType(), k56);
        zzae = new na2("languageIdentificationOptionalModuleLogEvent", xg6.u(hashMap56));
        zzcx k57 = xg6.k(60);
        HashMap hashMap57 = new HashMap();
        hashMap57.put(k57.annotationType(), k57);
        zzaf = new na2("faceDetectionOptionalModuleLogEvent", xg6.u(hashMap57));
        zzcx k58 = xg6.k(85);
        HashMap hashMap58 = new HashMap();
        hashMap58.put(k58.annotationType(), k58);
        zzag = new na2("documentDetectionOptionalModuleLogEvent", xg6.u(hashMap58));
        zzcx k59 = xg6.k(86);
        HashMap hashMap59 = new HashMap();
        hashMap59.put(k59.annotationType(), k59);
        zzah = new na2("documentCroppingOptionalModuleLogEvent", xg6.u(hashMap59));
        zzcx k60 = xg6.k(87);
        HashMap hashMap60 = new HashMap();
        hashMap60.put(k60.annotationType(), k60);
        zzai = new na2("documentEnhancementOptionalModuleLogEvent", xg6.u(hashMap60));
        zzcx k61 = xg6.k(55);
        HashMap hashMap61 = new HashMap();
        hashMap61.put(k61.annotationType(), k61);
        zzaj = new na2("nlClassifierOptionalModuleLogEvent", xg6.u(hashMap61));
        zzcx k62 = xg6.k(56);
        HashMap hashMap62 = new HashMap();
        hashMap62.put(k62.annotationType(), k62);
        zzak = new na2("nlClassifierClientLibraryLogEvent", xg6.u(hashMap62));
        zzcx k63 = xg6.k(57);
        HashMap hashMap63 = new HashMap();
        hashMap63.put(k63.annotationType(), k63);
        zzal = new na2("accelerationAllowlistLogEvent", xg6.u(hashMap63));
        zzcx k64 = xg6.k(62);
        HashMap hashMap64 = new HashMap();
        hashMap64.put(k64.annotationType(), k64);
        zzam = new na2("toxicityDetectionCreateEvent", xg6.u(hashMap64));
        zzcx k65 = xg6.k(63);
        HashMap hashMap65 = new HashMap();
        hashMap65.put(k65.annotationType(), k65);
        zzan = new na2("toxicityDetectionLoadEvent", xg6.u(hashMap65));
        zzcx k66 = xg6.k(64);
        HashMap hashMap66 = new HashMap();
        hashMap66.put(k66.annotationType(), k66);
        zzao = new na2("toxicityDetectionInferenceEvent", xg6.u(hashMap66));
        zzcx k67 = xg6.k(65);
        HashMap hashMap67 = new HashMap();
        hashMap67.put(k67.annotationType(), k67);
        zzap = new na2("barcodeDetectionOptionalModuleLogEvent", xg6.u(hashMap67));
        zzcx k68 = xg6.k(66);
        HashMap hashMap68 = new HashMap();
        hashMap68.put(k68.annotationType(), k68);
        zzaq = new na2("customImageLabelOptionalModuleLogEvent", xg6.u(hashMap68));
        zzcx k69 = xg6.k(67);
        HashMap hashMap69 = new HashMap();
        hashMap69.put(k69.annotationType(), k69);
        zzar = new na2("codeScannerScanApiEvent", xg6.u(hashMap69));
        zzcx k70 = xg6.k(68);
        HashMap hashMap70 = new HashMap();
        hashMap70.put(k70.annotationType(), k70);
        zzas = new na2("codeScannerOptionalModuleEvent", xg6.u(hashMap70));
        zzcx k71 = xg6.k(70);
        HashMap hashMap71 = new HashMap();
        hashMap71.put(k71.annotationType(), k71);
        zzat = new na2("onDeviceExplicitContentCreateLogEvent", xg6.u(hashMap71));
        zzcx k72 = xg6.k(71);
        HashMap hashMap72 = new HashMap();
        hashMap72.put(k72.annotationType(), k72);
        zzau = new na2("onDeviceExplicitContentLoadLogEvent", xg6.u(hashMap72));
        zzcx k73 = xg6.k(72);
        HashMap hashMap73 = new HashMap();
        hashMap73.put(k73.annotationType(), k73);
        zzav = new na2("onDeviceExplicitContentInferenceLogEvent", xg6.u(hashMap73));
        zzcx k74 = xg6.k(73);
        HashMap hashMap74 = new HashMap();
        hashMap74.put(k74.annotationType(), k74);
        zzaw = new na2("aggregatedOnDeviceExplicitContentLogEvent", xg6.u(hashMap74));
        zzcx k75 = xg6.k(74);
        HashMap hashMap75 = new HashMap();
        hashMap75.put(k75.annotationType(), k75);
        zzax = new na2("onDeviceFaceMeshCreateLogEvent", xg6.u(hashMap75));
        zzcx k76 = xg6.k(75);
        HashMap hashMap76 = new HashMap();
        hashMap76.put(k76.annotationType(), k76);
        zzay = new na2("onDeviceFaceMeshLoadLogEvent", xg6.u(hashMap76));
        zzcx k77 = xg6.k(76);
        HashMap hashMap77 = new HashMap();
        hashMap77.put(k77.annotationType(), k77);
        zzaz = new na2("onDeviceFaceMeshLogEvent", xg6.u(hashMap77));
        zzcx k78 = xg6.k(77);
        HashMap hashMap78 = new HashMap();
        hashMap78.put(k78.annotationType(), k78);
        zzaA = new na2("aggregatedOnDeviceFaceMeshLogEvent", xg6.u(hashMap78));
        zzcx k79 = xg6.k(78);
        HashMap hashMap79 = new HashMap();
        hashMap79.put(k79.annotationType(), k79);
        zzaB = new na2("smartReplyOptionalModuleLogEvent", xg6.u(hashMap79));
        zzcx k80 = xg6.k(80);
        HashMap hashMap80 = new HashMap();
        hashMap80.put(k80.annotationType(), k80);
        zzaC = new na2("textDetectionOptionalModuleLogEvent", xg6.u(hashMap80));
        zzcx k81 = xg6.k(81);
        HashMap hashMap81 = new HashMap();
        hashMap81.put(k81.annotationType(), k81);
        zzaD = new na2("onDeviceImageQualityAnalysisCreateLogEvent", xg6.u(hashMap81));
        zzcx k82 = xg6.k(82);
        HashMap hashMap82 = new HashMap();
        hashMap82.put(k82.annotationType(), k82);
        zzaE = new na2("onDeviceImageQualityAnalysisLoadLogEvent", xg6.u(hashMap82));
        zzcx k83 = xg6.k(83);
        HashMap hashMap83 = new HashMap();
        hashMap83.put(k83.annotationType(), k83);
        zzaF = new na2("onDeviceImageQualityAnalysisLogEvent", xg6.u(hashMap83));
        zzcx k84 = xg6.k(84);
        HashMap hashMap84 = new HashMap();
        hashMap84.put(k84.annotationType(), k84);
        zzaG = new na2("aggregatedOnDeviceImageQualityAnalysisLogEvent", xg6.u(hashMap84));
        zzcx k85 = xg6.k(88);
        HashMap hashMap85 = new HashMap();
        hashMap85.put(k85.annotationType(), k85);
        zzaH = new na2("imageQualityAnalysisOptionalModuleLogEvent", xg6.u(hashMap85));
        zzcx k86 = xg6.k(89);
        HashMap hashMap86 = new HashMap();
        hashMap86.put(k86.annotationType(), k86);
        zzaI = new na2("imageCaptioningOptionalModuleLogEvent", xg6.u(hashMap86));
        zzcx k87 = xg6.k(90);
        HashMap hashMap87 = new HashMap();
        hashMap87.put(k87.annotationType(), k87);
        zzaJ = new na2("onDeviceImageCaptioningCreateLogEvent", xg6.u(hashMap87));
        zzcx k88 = xg6.k(91);
        HashMap hashMap88 = new HashMap();
        hashMap88.put(k88.annotationType(), k88);
        zzaK = new na2("onDeviceImageCaptioningLoadLogEvent", xg6.u(hashMap88));
        zzcx k89 = xg6.k(92);
        HashMap hashMap89 = new HashMap();
        hashMap89.put(k89.annotationType(), k89);
        zzaL = new na2("onDeviceImageCaptioningInferenceLogEvent", xg6.u(hashMap89));
        zzcx k90 = xg6.k(93);
        HashMap hashMap90 = new HashMap();
        hashMap90.put(k90.annotationType(), k90);
        zzaM = new na2("aggregatedOnDeviceImageCaptioningInferenceLogEvent", xg6.u(hashMap90));
        zzcx k91 = xg6.k(94);
        HashMap hashMap91 = new HashMap();
        hashMap91.put(k91.annotationType(), k91);
        zzaN = new na2("onDeviceDocumentDetectionCreateLogEvent", xg6.u(hashMap91));
        zzcx k92 = xg6.k(95);
        HashMap hashMap92 = new HashMap();
        hashMap92.put(k92.annotationType(), k92);
        zzaO = new na2("onDeviceDocumentDetectionLoadLogEvent", xg6.u(hashMap92));
        zzcx k93 = xg6.k(96);
        HashMap hashMap93 = new HashMap();
        hashMap93.put(k93.annotationType(), k93);
        zzaP = new na2("onDeviceDocumentDetectionLogEvent", xg6.u(hashMap93));
        zzcx k94 = xg6.k(97);
        HashMap hashMap94 = new HashMap();
        hashMap94.put(k94.annotationType(), k94);
        zzaQ = new na2("aggregatedOnDeviceDocumentDetectionLogEvent", xg6.u(hashMap94));
        zzcx k95 = xg6.k(98);
        HashMap hashMap95 = new HashMap();
        hashMap95.put(k95.annotationType(), k95);
        zzaR = new na2("onDeviceDocumentCroppingCreateLogEvent", xg6.u(hashMap95));
        zzcx k96 = xg6.k(99);
        HashMap hashMap96 = new HashMap();
        hashMap96.put(k96.annotationType(), k96);
        zzaS = new na2("onDeviceDocumentCroppingLoadLogEvent", xg6.u(hashMap96));
        zzcx k97 = xg6.k(100);
        HashMap hashMap97 = new HashMap();
        hashMap97.put(k97.annotationType(), k97);
        zzaT = new na2("onDeviceDocumentCroppingLogEvent", xg6.u(hashMap97));
        zzcx k98 = xg6.k(MlKitException.NOT_ENOUGH_SPACE);
        HashMap hashMap98 = new HashMap();
        hashMap98.put(k98.annotationType(), k98);
        zzaU = new na2("aggregatedOnDeviceDocumentCroppingLogEvent", xg6.u(hashMap98));
        zzcx k99 = xg6.k(MlKitException.MODEL_HASH_MISMATCH);
        HashMap hashMap99 = new HashMap();
        hashMap99.put(k99.annotationType(), k99);
        zzaV = new na2("onDeviceDocumentEnhancementCreateLogEvent", xg6.u(hashMap99));
        zzcx k100 = xg6.k(103);
        HashMap hashMap100 = new HashMap();
        hashMap100.put(k100.annotationType(), k100);
        zzaW = new na2("onDeviceDocumentEnhancementLoadLogEvent", xg6.u(hashMap100));
        zzcx k101 = xg6.k(104);
        HashMap hashMap101 = new HashMap();
        hashMap101.put(k101.annotationType(), k101);
        zzaX = new na2("onDeviceDocumentEnhancementLogEvent", xg6.u(hashMap101));
        zzcx k102 = xg6.k(105);
        HashMap hashMap102 = new HashMap();
        hashMap102.put(k102.annotationType(), k102);
        zzaY = new na2("aggregatedOnDeviceDocumentEnhancementLogEvent", xg6.u(hashMap102));
        zzcx k103 = xg6.k(106);
        HashMap hashMap103 = new HashMap();
        hashMap103.put(k103.annotationType(), k103);
        zzaZ = new na2("scannerAutoZoomEvent", xg6.u(hashMap103));
        zzcx k104 = xg6.k(107);
        HashMap hashMap104 = new HashMap();
        hashMap104.put(k104.annotationType(), k104);
        zzba = new na2("lowLightAutoExposureComputationEvent", xg6.u(hashMap104));
        zzcx k105 = xg6.k(108);
        HashMap hashMap105 = new HashMap();
        hashMap105.put(k105.annotationType(), k105);
        zzbb = new na2("lowLightFrameProcessEvent", xg6.u(hashMap105));
        zzcx k106 = xg6.k(109);
        HashMap hashMap106 = new HashMap();
        hashMap106.put(k106.annotationType(), k106);
        zzbc = new na2("lowLightSceneDetectionEvent", xg6.u(hashMap106));
        zzcx k107 = xg6.k(110);
        HashMap hashMap107 = new HashMap();
        hashMap107.put(k107.annotationType(), k107);
        zzbd = new na2("onDeviceStainRemovalLogEvent", xg6.u(hashMap107));
        zzcx k108 = xg6.k(111);
        HashMap hashMap108 = new HashMap();
        hashMap108.put(k108.annotationType(), k108);
        zzbe = new na2("aggregatedOnDeviceStainRemovalLogEvent", xg6.u(hashMap108));
        zzbf = xg6.C(112, na2.a("stainRemovalOptionalModuleLogEvent"));
        zzbg = xg6.C(113, na2.a("onDeviceShadowRemovalLogEvent"));
        zzbh = xg6.C(114, na2.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        zzbi = xg6.C(115, na2.a("shadowRemovalOptionalModuleLogEvent"));
        zzbj = xg6.C(116, na2.a("onDeviceDigitalInkSegmentationLogEvent"));
        zzbk = xg6.C(117, na2.a("onDeviceDocumentScannerStartLogEvent"));
        zzbl = xg6.C(118, na2.a("onDeviceDocumentScannerFinishLogEvent"));
        zzbm = xg6.C(119, na2.a("onDeviceDocumentScannerUiStartLogEvent"));
        zzbn = xg6.C(120, na2.a("onDeviceDocumentScannerUiFinishLogEvent"));
        zzbo = xg6.C(121, na2.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        zzbp = xg6.C(122, na2.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        zzbq = xg6.C(123, na2.a("onDeviceDocumentScannerUiCreateLogEvent"));
        zzbr = xg6.C(ModelPPM.MAX_FREQ, na2.a("onDeviceSubjectSegmentationCreateLogEvent"));
        zzbs = xg6.C(125, na2.a("onDeviceSubjectSegmentationLoadLogEvent"));
        zzbt = xg6.C(126, na2.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        zzbu = xg6.C(127, na2.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        zzbv = xg6.C(128, na2.a("subjectSegmentationOptionalModuleLogEvent"));
        zzbw = xg6.C(129, na2.a("documentScannerUiModuleScreenViewEvent"));
        zzbx = xg6.C(130, na2.a("documentScannerUiModuleScreenClickEvent"));
        zzby = xg6.C(131, na2.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private zzio() {
    }

    @Override // defpackage.y32
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzoy zzoyVar = (zzoy) obj;
        rh4 rh4Var = (rh4) obj2;
        rh4Var.add(zzb, zzoyVar.zzf());
        rh4Var.add(zzc, zzoyVar.zzc());
        rh4Var.add(zzd, (Object) null);
        rh4Var.add(zze, zzoyVar.zzb());
        rh4Var.add(zzf, (Object) null);
        rh4Var.add(zzg, (Object) null);
        rh4Var.add(zzh, (Object) null);
        rh4Var.add(zzi, (Object) null);
        rh4Var.add(zzj, (Object) null);
        rh4Var.add(zzk, (Object) null);
        rh4Var.add(zzl, zzoyVar.zze());
        rh4Var.add(zzm, zzoyVar.zzd());
        rh4Var.add(zzn, (Object) null);
        rh4Var.add(zzo, (Object) null);
        rh4Var.add(zzp, (Object) null);
        rh4Var.add(zzq, (Object) null);
        rh4Var.add(zzr, (Object) null);
        rh4Var.add(zzs, (Object) null);
        rh4Var.add(zzt, (Object) null);
        rh4Var.add(zzu, (Object) null);
        rh4Var.add(zzv, (Object) null);
        rh4Var.add(zzw, (Object) null);
        rh4Var.add(zzx, (Object) null);
        rh4Var.add(zzy, (Object) null);
        rh4Var.add(zzz, (Object) null);
        rh4Var.add(zzA, (Object) null);
        rh4Var.add(zzB, (Object) null);
        rh4Var.add(zzC, (Object) null);
        rh4Var.add(zzD, (Object) null);
        rh4Var.add(zzE, (Object) null);
        rh4Var.add(zzF, (Object) null);
        rh4Var.add(zzG, (Object) null);
        rh4Var.add(zzH, (Object) null);
        rh4Var.add(zzI, (Object) null);
        rh4Var.add(zzJ, (Object) null);
        rh4Var.add(zzK, (Object) null);
        rh4Var.add(zzL, (Object) null);
        rh4Var.add(zzM, (Object) null);
        rh4Var.add(zzN, (Object) null);
        rh4Var.add(zzO, (Object) null);
        rh4Var.add(zzP, (Object) null);
        rh4Var.add(zzQ, (Object) null);
        rh4Var.add(zzR, (Object) null);
        rh4Var.add(zzS, (Object) null);
        rh4Var.add(zzT, (Object) null);
        rh4Var.add(zzU, (Object) null);
        rh4Var.add(zzV, zzoyVar.zza());
        rh4Var.add(zzW, (Object) null);
        rh4Var.add(zzX, (Object) null);
        rh4Var.add(zzY, (Object) null);
        rh4Var.add(zzZ, (Object) null);
        rh4Var.add(zzaa, (Object) null);
        rh4Var.add(zzab, (Object) null);
        rh4Var.add(zzac, (Object) null);
        rh4Var.add(zzad, (Object) null);
        rh4Var.add(zzae, (Object) null);
        rh4Var.add(zzaf, (Object) null);
        rh4Var.add(zzag, (Object) null);
        rh4Var.add(zzah, (Object) null);
        rh4Var.add(zzai, (Object) null);
        rh4Var.add(zzaj, (Object) null);
        rh4Var.add(zzak, (Object) null);
        rh4Var.add(zzal, (Object) null);
        rh4Var.add(zzam, (Object) null);
        rh4Var.add(zzan, (Object) null);
        rh4Var.add(zzao, (Object) null);
        rh4Var.add(zzap, (Object) null);
        rh4Var.add(zzaq, (Object) null);
        rh4Var.add(zzar, (Object) null);
        rh4Var.add(zzas, (Object) null);
        rh4Var.add(zzat, (Object) null);
        rh4Var.add(zzau, (Object) null);
        rh4Var.add(zzav, (Object) null);
        rh4Var.add(zzaw, (Object) null);
        rh4Var.add(zzax, (Object) null);
        rh4Var.add(zzay, (Object) null);
        rh4Var.add(zzaz, (Object) null);
        rh4Var.add(zzaA, (Object) null);
        rh4Var.add(zzaB, (Object) null);
        rh4Var.add(zzaC, (Object) null);
        rh4Var.add(zzaD, (Object) null);
        rh4Var.add(zzaE, (Object) null);
        rh4Var.add(zzaF, (Object) null);
        rh4Var.add(zzaG, (Object) null);
        rh4Var.add(zzaH, (Object) null);
        rh4Var.add(zzaI, (Object) null);
        rh4Var.add(zzaJ, (Object) null);
        rh4Var.add(zzaK, (Object) null);
        rh4Var.add(zzaL, (Object) null);
        rh4Var.add(zzaM, (Object) null);
        rh4Var.add(zzaN, (Object) null);
        rh4Var.add(zzaO, (Object) null);
        rh4Var.add(zzaP, (Object) null);
        rh4Var.add(zzaQ, (Object) null);
        rh4Var.add(zzaR, (Object) null);
        rh4Var.add(zzaS, (Object) null);
        rh4Var.add(zzaT, (Object) null);
        rh4Var.add(zzaU, (Object) null);
        rh4Var.add(zzaV, (Object) null);
        rh4Var.add(zzaW, (Object) null);
        rh4Var.add(zzaX, (Object) null);
        rh4Var.add(zzaY, (Object) null);
        rh4Var.add(zzaZ, (Object) null);
        rh4Var.add(zzba, (Object) null);
        rh4Var.add(zzbb, (Object) null);
        rh4Var.add(zzbc, (Object) null);
        rh4Var.add(zzbd, (Object) null);
        rh4Var.add(zzbe, (Object) null);
        rh4Var.add(zzbf, (Object) null);
        rh4Var.add(zzbg, (Object) null);
        rh4Var.add(zzbh, (Object) null);
        rh4Var.add(zzbi, (Object) null);
        rh4Var.add(zzbj, (Object) null);
        rh4Var.add(zzbk, (Object) null);
        rh4Var.add(zzbl, (Object) null);
        rh4Var.add(zzbm, (Object) null);
        rh4Var.add(zzbn, (Object) null);
        rh4Var.add(zzbo, (Object) null);
        rh4Var.add(zzbp, (Object) null);
        rh4Var.add(zzbq, (Object) null);
        rh4Var.add(zzbr, (Object) null);
        rh4Var.add(zzbs, (Object) null);
        rh4Var.add(zzbt, (Object) null);
        rh4Var.add(zzbu, (Object) null);
        rh4Var.add(zzbv, (Object) null);
        rh4Var.add(zzbw, (Object) null);
        rh4Var.add(zzbx, (Object) null);
        rh4Var.add(zzby, (Object) null);
    }
}
