package defpackage;

import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
/* compiled from: r8-map-id-0dd4387375ec438f6a4c042bfe6cb4a3262713dcd4829883cccf19288831b1df */
/* renamed from: d36  reason: default package */
/* loaded from: classes.dex */
public abstract class d36 {
    public static final Map a = c14.m0(new vr4("Бэтмен", "Бэ́тмен"), new vr4("Бэтмэн", "Бэ́тмэн"), new vr4("Джокер", "Джо́кер"), new vr4("Готэм", "Го́тэм"), new vr4("Зельда", "Зе́льда"), new vr4("Лейтон", "Ле́йтон"), new vr4("Пикачу", "Пикачу́"), new vr4("Покемон", "Покемо́н"), new vr4("Покемоны", "Покемо́ны"), new vr4("Марио", "Ма́рио"), new vr4("Луиджи", "Луи́джи"), new vr4("Баузер", "Ба́узер"), new vr4("Боузер", "Бо́узер"), new vr4("Кастлвания", "Кастлва́ния"), new vr4("Кастлевания", "Кастлева́ния"), new vr4("Эджворт", "Э́джворт"), new vr4("Феникс Райт", "Фе́никс Райт"), new vr4("Гамшу", "Гамшу́"), new vr4("Метроид", "Метро́ид"), new vr4("Самус", "Са́мус"), new vr4("Соник", "Со́ник"), new vr4("Наклз", "На́клз"), new vr4("Тейлз", "Те́йлз"), new vr4("Тейлс", "Те́йлс"), new vr4("Клауд", "Кла́уд"), new vr4("Сефирот", "Сефиро́т"), new vr4("Данте", "Да́нте"), new vr4("Кратос", "Кра́тос"), new vr4("Снейк", "Снейк"), new vr4("Вескер", "Ве́скер"), new vr4("подземелье", "подземе́лье"), new vr4("подземелья", "подземе́лья"), new vr4("подземелий", "подземе́лий"), new vr4("инвентарь", "инвента́рь"), new vr4("артефакт", "артефа́кт"), new vr4("артефакты", "артефа́кты"), new vr4("доспехи", "доспе́хи"), new vr4("оружие", "ору́жие"), new vr4("заклинание", "заклина́ние"), new vr4("заклинания", "заклина́ния"), new vr4("исцеление", "исцеле́ние"), new vr4("сундук", "сунду́к"), new vr4("сундуки", "сундуки́"), new vr4("снаряжение", "снаряже́ние"), new vr4("эликсир", "эликси́р"), new vr4("зелье", "зе́лье"), new vr4("зелья", "зе́лья"), new vr4("уровень", "у́ровень"), new vr4("уровня", "у́ровня"), new vr4("уровне", "у́ровне"), new vr4("опыт", "о́пыт"), new vr4("урон", "уро́н"), new vr4("защита", "защи́та"), new vr4("атака", "ата́ка"), new vr4("способность", "спосо́бность"), new vr4("способности", "спосо́бности"), new vr4("головоломка", "головоло́мка"), new vr4("головоломки", "головоло́мки"), new vr4("загадка", "зага́дка"), new vr4("загадки", "зага́дки"), new vr4("препятствие", "препя́тствие"), new vr4("препятствия", "препя́тствия"), new vr4("королевство", "короле́вство"), new vr4("принцесса", "принце́сса"), new vr4("чудовище", "чудо́вище"), new vr4("чудовища", "чудо́вища"), new vr4("сохранение", "сохране́ние"), new vr4("загрузка", "загру́зка"));
    public static final List b = hf.c0(new vr4(Pattern.compile("\\bHP\\b", 2), "хит-поинты"), new vr4(Pattern.compile("\\bMP\\b", 2), "мана-поинты"), new vr4(Pattern.compile("\\bEXP\\b", 2), "очки опыта"), new vr4(Pattern.compile("\\bXP\\b", 2), "очки опыта"), new vr4(Pattern.compile("\\bNPC\\b", 2), "неигровой персонаж"), new vr4(Pattern.compile("\\bLVL?\\b", 2), "уровень"), new vr4(Pattern.compile("\\bATK\\b", 2), "атака"), new vr4(Pattern.compile("\\bDEF\\b", 2), "защита"), new vr4(Pattern.compile("\\bCRIT\\b", 2), "критический удар"), new vr4(Pattern.compile("\\bNDS\\b", 2), "Ниндендо Ди-Эс"), new vr4(Pattern.compile("\\bDS\\b", 2), "Ди-Эс"), new vr4(Pattern.compile("\\b3DS\\b", 2), "Три-Ди-Эс"), new vr4(Pattern.compile("\\bKO\\b", 2), "нокаут"));
    public static final List c = hf.c0(new vr4(Pattern.compile("\\bX\\b"), "десятая"), new vr4(Pattern.compile("\\bIX\\b"), "девятая"), new vr4(Pattern.compile("\\bVIII\\b"), "восьмая"), new vr4(Pattern.compile("\\bVII\\b"), "седьмая"), new vr4(Pattern.compile("\\bVI\\b"), "шестая"), new vr4(Pattern.compile("\\bIV\\b"), "четвертая"), new vr4(Pattern.compile("\\bV\\b"), "пятая"), new vr4(Pattern.compile("\\bIII\\b"), "третья"), new vr4(Pattern.compile("\\bII\\b"), "вторая"), new vr4(Pattern.compile("\\bI\\b"), "первая"));
}
