package defpackage;

import java.util.List;
/* compiled from: r8-map-id-0dd4387375ec438f6a4c042bfe6cb4a3262713dcd4829883cccf19288831b1df */
/* renamed from: dw1  reason: default package */
/* loaded from: classes.dex */
public abstract class dw1 {
    public static final List a = hf.c0(new mj5(-1, "Native compMode - keep packed control plane"), new mj5(0, "compMode 0 - sample 3D path, normal composite branch"), new mj5(1, "compMode 1 - 3D-aware branch with direct 2D/3D selection"), new mj5(2, "compMode 2 - 3D-aware blend branch"), new mj5(3, "compMode 3 - 3D-aware alternate blend branch"), new mj5(4, "compMode 4 - capture-backed 3D placeholder branch"), new mj5(5, "compMode 5 - reserved/debug passthrough branch"), new mj5(6, "compMode 6 - reserved/debug passthrough branch"), new mj5(7, "compMode 7 - no live 3D sample unless temporal fallback is marked"));
    public static final List b = hf.c0(new lj5("BG0 - first static or 3D background layer", 0, "Nintendo DS BG0. Code gate: DISPCNT bit 8; DrawBG_Text, or DrawBG_3D on Engine A when DISPCNT bit 3 selects the 3D background."), new lj5("BG1 - static background layer", 1, "Nintendo DS BG1. Code gate: DISPCNT bit 9; currently routes through DrawBG_Text in the software 2D compositor."), new lj5("BG2 - static, affine, affine extended or large screen background", 2, "Nintendo DS BG2. Code gate: DISPCNT bit 10; routes through DrawBG_Text, DrawBG_Affine, DrawBG_Extended or DrawBG_Large depending on BG mode and BGCNT."), new lj5("BG3 - static, affine or affine extended background", 3, "Nintendo DS BG3. Code gate: DISPCNT bit 11; routes through DrawBG_Text, DrawBG_Affine or DrawBG_Extended depending on BG mode and BGCNT."));
    public static final List c = hf.c0(new qj5("Priority 0 - frontmost", 0, "Highest Nintendo DS priority; this layer is drawn closest to the viewer."), new qj5("Priority 1", 1, "Second-highest Nintendo DS priority."), new qj5("Priority 2", 2, "Second-lowest Nintendo DS priority."), new qj5("Priority 3 - backmost", 3, "Lowest Nintendo DS priority; this layer is drawn furthest back."));
    public static final List d = hf.c0(new pj5("OBJ OAM index 0..31 - frontmost order bucket", 0, "OAM entries 0-31. Code gate: `sprnum / 32` in `DrawSprites`; lower OBJ indices are drawn later for equal priority and usually appear in front."), new pj5("OBJ OAM index 32..63", 1, "OAM entries 32-63. Code gate: `sprnum / 32` in `DrawSprites`; useful for separating grouped composite sprites with the same OBJ priority."), new pj5("OBJ OAM index 64..95", 2, "OAM entries 64-95. Code gate: `sprnum / 32` in `DrawSprites`; later than 96-127 but behind lower OAM index buckets at equal priority."), new pj5("OBJ OAM index 96..127 - backmost order bucket", 3, "OAM entries 96-127. Code gate: `sprnum / 32` in `DrawSprites`; highest OBJ indices are drawn first for equal priority and usually sit furthest back."));
}
