jadx.core.utils.exceptions.JadxRuntimeException: Failed to generate code for class: defpackage.xb2
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:121)
	at jadx.core.dex.nodes.ClassNode.decompile(ClassNode.java:383)
	at jadx.core.dex.nodes.ClassNode.getCode(ClassNode.java:331)
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Code generation error after restart
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:52)
	at jadx.core.codegen.CodeGen.generateJavaCode(CodeGen.java:34)
	at jadx.core.codegen.CodeGen.generate(CodeGen.java:22)
	at jadx.core.ProcessClass.process(ProcessClass.java:77)
	at jadx.core.ProcessClass.generateCode(ProcessClass.java:115)
	... 2 more
Caused by: jadx.core.utils.exceptions.JadxRuntimeException: Method generation error
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:309)
	at jadx.core.codegen.ClassGen.lambda$addInnerClsAndMethods$2(ClassGen.java:272)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:186)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:261)
	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.end(ReferencePipeline.java:284)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:571)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:153)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:176)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:632)
	at jadx.core.codegen.ClassGen.addInnerClsAndMethods(ClassGen.java:268)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:257)
	at jadx.core.codegen.ClassGen.addClassBody(ClassGen.java:241)
	at jadx.core.codegen.ClassGen.addClassCode(ClassGen.java:132)
	at jadx.core.codegen.ClassGen.makeClass(ClassGen.java:95)
	at jadx.core.codegen.CodeGen.wrapCodeGen(CodeGen.java:50)
	... 6 more
Caused by: jadx.core.utils.exceptions.CodegenException: Error generate insn: 0x005b: IF  (wrap: boolean : 0x0057: INVOKE  (r2v7 boolean A[REMOVE]) = 
  (wrap: android.net.Uri : 0x0055: IGET  (r2v6 android.net.Uri A[REMOVE]) = (wrap: pq5 : 0x0053: CHECK_CAST (r2v5 pq5 A[REMOVE]) = (pq5) (r1v12 'obj' java.lang.Object)) pq5.d android.net.Uri)
  (r8v1 'uri' android.net.Uri)
 type: STATIC call: nb3.k(java.lang.Object, java.lang.Object):boolean) != false  -> B:73:0x005f in method: xb2.l(android.net.Uri, s41):java.lang.Object, file: classes.dex
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:309)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:272)
	at jadx.core.codegen.RegionGen.makeSimpleBlock(RegionGen.java:91)
	at jadx.core.dex.nodes.IBlock.generate(IBlock.java:15)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
	at jadx.core.codegen.RegionGen.makeRegionIndent(RegionGen.java:80)
	at jadx.core.codegen.RegionGen.makeLoop(RegionGen.java:175)
	at jadx.core.dex.regions.loops.LoopRegion.generate(LoopRegion.java:171)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
	at jadx.core.dex.regions.Region.generate(Region.java:35)
	at jadx.core.codegen.RegionGen.makeRegion(RegionGen.java:63)
	at jadx.core.codegen.MethodGen.addRegionInsns(MethodGen.java:296)
	at jadx.core.codegen.MethodGen.addInstructions(MethodGen.java:275)
	at jadx.core.codegen.ClassGen.addMethodCode(ClassGen.java:377)
	at jadx.core.codegen.ClassGen.addMethod(ClassGen.java:306)
	... 24 more
Caused by: jadx.core.utils.exceptions.CodegenException: IF instruction can be used only in fallback mode
	at jadx.core.codegen.InsnGen.fallbackOnlyInsn(InsnGen.java:686)
	at jadx.core.codegen.InsnGen.makeInsnBody(InsnGen.java:544)
	at jadx.core.codegen.InsnGen.makeInsn(InsnGen.java:302)
	... 40 more

